import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "El problema: muebles que no combinan",
    explanation: `Imaginá que estás armando una app de decoración de interiores. Tenés tres estilos de muebles: Victorian (ornamental, madera oscura), Modern (minimalista, líneas limpias) y ArtDeco (geométrico, dorado). Cada estilo tiene su propia silla, mesa y sofá.\n\n**El problema**: si el usuario elige "Victorian" pero tu código crea una silla Modern y una mesa ArtDeco, el resultado es un desastre visual. Los muebles de una familia DEBEN usarse juntos — no podés mezclar estilos.\n\n**La solución**: Abstract Factory. En vez de crear muebles sueltos, creás una **fábrica por familia**. Cada fábrica garantiza que todos los muebles que produce sean del mismo estilo. El cliente dice "dame la fábrica Victorian" y recibe silla + mesa + sofá que combinan perfecto.\n\n**Las clases del patrón**: definís una 'FurnitureFactory' base con métodos como 'createChair()', 'createTable()' y 'createSofa()'. Después creás fábricas concretas: 'VictorianFactory' produce muebles victorianos, 'ModernFactory' produce muebles modernos, y 'ArtDecoFactory' produce muebles art decó. Cada fábrica garantiza que todos sus productos sean del mismo estilo.\n\n**Diferencia con Factory Method**: Factory Method crea UN tipo de objeto según un parámetro. Abstract Factory crea una FAMILIA COMPLETA de objetos relacionados que deben ser compatibles entre sí.`,
    code: {
      typescript: `// ❌ Sin Abstract Factory — mezcla estilos\nfunction furnishRoomBad(style: string) {\n  // Si olvidás cambiar uno, tenés un Frankenstein\n  const chair = style === 'victorian'\n    ? new VictorianChair()\n    : new ModernChair();\n  const table = new ArtDecoTable(); // ¡Error! Mezclamos estilos\n  const sofa = new VictorianSofa();\n}\n\n// ✅ Con Abstract Factory — familia garantizada\nfunction furnishRoomGood(factory: FurnitureFactory) {\n  const chair = factory.createChair();   // Mismo estilo\n  const table = factory.createTable();   // Mismo estilo\n  const sofa = factory.createSofa();     // Mismo estilo\n}`,
      javascript: `// ❌ Sin Abstract Factory — mezcla estilos\nfunction furnishRoomBad(style) {\n  const chair = style === 'victorian'\n    ? new VictorianChair()\n    : new ModernChair();\n  const table = new ArtDecoTable(); // ¡Error! Mezclamos estilos\n  const sofa = new VictorianSofa();\n}\n\n// ✅ Con Abstract Factory — familia garantizada\nfunction furnishRoomGood(factory) {\n  const chair = factory.createChair();   // Mismo estilo\n  const table = factory.createTable();   // Mismo estilo\n  const sofa = factory.createSofa();     // Mismo estilo\n}`,
    },
  },
  {
    index: 1,
    title: "Definí las clases base y la primera familia",
    explanation: `Primero definimos las **clases base** para cada tipo de producto: \`Chair\`, \`Table\` y \`Sofa\`. Cada una tiene \`render()\` (para mostrar el mueble) y \`getStyle()\` (para devolver el nombre del estilo). Estas clases base son la abstracción — no muestran nada concreto, pero establecen el contrato que TODAS las familias deben cumplir.\n\nDespués creamos la **primera familia concreta**: Victorian. \`VictorianChair\`, \`VictorianTable\` y \`VictorianSofa\` extienden sus clases base y devuelven \`'Victorian'\` en \`getStyle()\`.\n\n**Clave**: cada producto concreto sabe qué estilo es. Esto parece obvio, pero es lo que permite que el código cliente verifique compatibilidad sin saber qué fábrica está usando.`,
    code: {
      typescript: `class Chair {\n  render() { return ''; }\n  getStyle() { return ''; }\n}\n\nclass Table {\n  render() { return ''; }\n  getStyle() { return ''; }\n}\n\nclass Sofa {\n  render() { return ''; }\n  getStyle() { return ''; }\n}\n\n// Victorian family\nclass VictorianChair extends Chair {\n  render() { return 'Victorian Chair — ornamental wood'; }\n  getStyle() { return 'Victorian'; }\n}\n\nclass VictorianTable extends Table {\n  render() { return 'Victorian Table — dark oak'; }\n  getStyle() { return 'Victorian'; }\n}\n\nclass VictorianSofa extends Sofa {\n  render() { return 'Victorian Sofa — velvet upholstery'; }\n  getStyle() { return 'Victorian'; }\n}`,
      javascript: `class Chair {\n  render() { return ''; }\n  getStyle() { return ''; }\n}\n\nclass Table {\n  render() { return ''; }\n  getStyle() { return ''; }\n}\n\nclass Sofa {\n  render() { return ''; }\n  getStyle() { return ''; }\n}\n\n// Victorian family\nclass VictorianChair extends Chair {\n  render() { return 'Victorian Chair — ornamental wood'; }\n  getStyle() { return 'Victorian'; }\n}\n\nclass VictorianTable extends Table {\n  render() { return 'Victorian Table — dark oak'; }\n  getStyle() { return 'Victorian'; }\n}\n\nclass VictorianSofa extends Sofa {\n  render() { return 'Victorian Sofa — velvet upholstery'; }\n  getStyle() { return 'Victorian'; }\n}`,
    },
  },
  {
    index: 2,
    title: "Agregá las familias Modern y ArtDeco",
    explanation: `Ahora repetimos la misma estructura para las otras dos familias. \`ModernChair\`, \`ModernTable\` y \`ModernSofa\` son minimalistas con líneas limpias. \`ArtDecoChair\`, \`ArtDecoTable\` y \`ArtDecoSofa\` son geométricos con dorado.\n\n**Patrón clave**: cada familia sigue exactamente la misma estructura — extiende las clases base y devuelve su estilo en \`getStyle()\`. Esto es lo que hace que el patrón sea reemplazable: cualquier fábrica puede producir cualquier familia, y el código cliente funciona igual.\n\nEn total tenemos **9 clases concretas** (3 productos × 3 familias). Si agregaras un cuarto estilo (ej. Industrial), serían 12. El patrón escala agregando familias sin tocar el código existente.`,
    code: {
      typescript: `// Modern family\nclass ModernChair extends Chair {\n  render() { return 'Modern Chair — minimalist'; }\n  getStyle() { return 'Modern'; }\n}\n\nclass ModernTable extends Table {\n  render() { return 'Modern Table — clean lines'; }\n  getStyle() { return 'Modern'; }\n}\n\nclass ModernSofa extends Sofa {\n  render() { return 'Modern Sofa — sleek design'; }\n  getStyle() { return 'Modern'; }\n}\n\n// ArtDeco family\nclass ArtDecoChair extends Chair {\n  render() { return 'ArtDeco Chair — geometric'; }\n  getStyle() { return 'ArtDeco'; }\n}\n\nclass ArtDecoTable extends Table {\n  render() { return 'ArtDeco Table — golden accents'; }\n  getStyle() { return 'ArtDeco'; }\n}\n\nclass ArtDecoSofa extends Sofa {\n  render() { return 'ArtDeco Sofa — bold shapes'; }\n  getStyle() { return 'ArtDeco'; }\n}`,
      javascript: `// Modern family\nclass ModernChair extends Chair {\n  render() { return 'Modern Chair — minimalist'; }\n  getStyle() { return 'Modern'; }\n}\n\nclass ModernTable extends Table {\n  render() { return 'Modern Table — clean lines'; }\n  getStyle() { return 'Modern'; }\n}\n\nclass ModernSofa extends Sofa {\n  render() { return 'Modern Sofa — sleek design'; }\n  getStyle() { return 'Modern'; }\n}\n\n// ArtDeco family\nclass ArtDecoChair extends Chair {\n  render() { return 'ArtDeco Chair — geometric'; }\n  getStyle() { return 'ArtDeco'; }\n}\n\nclass ArtDecoTable extends Table {\n  render() { return 'ArtDeco Table — golden accents'; }\n  getStyle() { return 'ArtDeco'; }\n}\n\nclass ArtDecoSofa extends Sofa {\n  render() { return 'ArtDeco Sofa — bold shapes'; }\n  getStyle() { return 'ArtDeco'; }\n}`,
    },
  },
  {
    index: 3,
    title: "Creá las fábricas y furnishRoom()",
    explanation: `Este es el paso que completa el patrón. \`FurnitureFactory\` es la **clase base de fábrica** — define los métodos \`createChair()\`, \`createTable()\` y \`createSofa()\`. Cada fábrica concreta (\`VictorianFactory\`, \`ModernFactory\`, \`ArtDecoFactory\`) extiende esta base y produce los productos de SU familia.\n\n**La magia**: \`furnishRoom(factory)\` recibe CUALQUIER fábrica y crea un mueble completo. No sabe si es Victorian, Modern o ArtDeco — solo llama a los métodos de creación y usa los resultados. Si mañana agregás un estilo Industrial, \`furnishRoom\` no cambia ni una línea.\n\n**Inversión de control**: el cliente no elige qué crear — le pasan una fábrica y confía en que produce la familia correcta. Esto garantiza que todos los muebles sean del mismo estilo, siempre.`,
    code: {
      typescript: `class FurnitureFactory {\n  createChair() { return new Chair(); }\n  createTable() { return new Table(); }\n  createSofa() { return new Sofa(); }\n}\n\nclass VictorianFactory extends FurnitureFactory {\n  createChair() { return new VictorianChair(); }\n  createTable() { return new VictorianTable(); }\n  createSofa() { return new VictorianSofa(); }\n}\n\nclass ModernFactory extends FurnitureFactory {\n  createChair() { return new ModernChair(); }\n  createTable() { return new ModernTable(); }\n  createSofa() { return new ModernSofa(); }\n}\n\nclass ArtDecoFactory extends FurnitureFactory {\n  createChair() { return new ArtDecoChair(); }\n  createTable() { return new ArtDecoTable(); }\n  createSofa() { return new ArtDecoSofa(); }\n}\n\n// Cliente — funciona con CUALQUIER fábrica\nfunction furnishRoom(factory) {\n  const chair = factory.createChair();\n  const table = factory.createTable();\n  const sofa = factory.createSofa();\n  return chair.getStyle() + ' ' + table.getStyle() + ' ' + sofa.getStyle();\n}\n\n// Uso:\nconsole.log(furnishRoom(new VictorianFactory())); // "Victorian Victorian Victorian"\nconsole.log(furnishRoom(new ModernFactory()));     // "Modern Modern Modern"\nconsole.log(furnishRoom(new ArtDecoFactory()));    // "ArtDeco ArtDeco ArtDeco"`,
      javascript: `class FurnitureFactory {\n  createChair() { return new Chair(); }\n  createTable() { return new Table(); }\n  createSofa() { return new Sofa(); }\n}\n\nclass VictorianFactory extends FurnitureFactory {\n  createChair() { return new VictorianChair(); }\n  createTable() { return new VictorianTable(); }\n  createSofa() { return new VictorianSofa(); }\n}\n\nclass ModernFactory extends FurnitureFactory {\n  createChair() { return new ModernChair(); }\n  createTable() { return new ModernTable(); }\n  createSofa() { return new ModernSofa(); }\n}\n\nclass ArtDecoFactory extends FurnitureFactory {\n  createChair() { return new ArtDecoChair(); }\n  createTable() { return new ArtDecoTable(); }\n  createSofa() { return new ArtDecoSofa(); }\n}\n\n// Cliente — funciona con CUALQUIER fábrica\nfunction furnishRoom(factory) {\n  const chair = factory.createChair();\n  const table = factory.createTable();\n  const sofa = factory.createSofa();\n  return chair.getStyle() + ' ' + table.getStyle() + ' ' + sofa.getStyle();\n}\n\n// Uso:\nconsole.log(furnishRoom(new VictorianFactory())); // "Victorian Victorian Victorian"\nconsole.log(furnishRoom(new ModernFactory()));     // "Modern Modern Modern"\nconsole.log(furnishRoom(new ArtDecoFactory()));    // "ArtDeco ArtDeco ArtDeco"`,
    },
  },
];

export const abstractFactoryGuided = buildGuidedExercise(
  "abstract-factory",
  "Abstract Factory — Modo Guiado",
  steps
);
