import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "El problema: APIs incompatibles",
    explanation: `El patrón **Adapter** resuelve un problema muy común: tenés dos o más clases que hacen lo que necesitás, pero no podés usarlas juntas porque tienen interfaces diferentes. En este ejercicio, tenés dos proveedores de pago — \`StripeAPI\` y \`PayPalAPI\` — cada uno con su propia forma de procesar pagos.\n\n**StripeAPI** usa \`charge({ amount_in_cents, currency_code })\` — espera el monto en centavos y un código de moneda.\n\n**PayPalAPI** usa \`processPayment(value, coin)\` — espera el monto como número y el nombre de la moneda como string.\n\nNo podés usar ambas directamente porque cada una tiene métodos, parámetros y formatos de retorno diferentes.\n\n**La solución**: crear una clase base \`PaymentProvider\` que defina la interfaz que el cliente espera (\`pay()\` y \`refund()\`), y luego crear **adaptadores** que traduzcan las llamadas de cada proveedor a esa interfaz común.`,
    code: {
      typescript: `// El problema: APIs incompatibles\n// StripeAPI usa charge({ amount_in_cents, currency_code })\n// PayPalAPI usa processPayment(value, coin)\n// No se pueden usar intercambiablemente...\n\n// La solución: PaymentProvider + Adaptadores`,
      javascript: `// El problema: APIs incompatibles\n// StripeAPI usa charge({ amount_in_cents, currency_code })\n// PayPalAPI usa processPayment(value, coin)\n// No se pueden usar intercambiablemente...\n\n// La solución: PaymentProvider + Adaptadores`,
    },
  },
  {
    index: 1,
    title: "Creá las clases de los proveedores externos",
    explanation: `Primero definimos las **clases adaptadas** — las APIs externas que ya existen y que no podemos modificar. Estas simulan los SDKs reales de Stripe y PayPal.\n\n\`StripeAPI\` tiene un método \`charge()\` que recibe un objeto con \`amount_in_cents\` (monto en centavos) y \`currency_code\` (código de moneda). Devuelve un objeto con \`id\` y \`status\`.\n\n\`PayPalAPI\` tiene un método \`processPayment()\` que recibe \`value\` (monto) y \`coin\` (moneda). Devuelve un objeto con \`confirmation\` y \`state\`.\n\nNotá que los nombres de los métodos, los parámetros y los formatos de retorno son **completamente diferentes**. Esto es lo que pasa cuando integrás servicios de terceros.\n\n**Estas clases no se modifican**. El patrón Adapter trabaja con clases existentes tal como son.`,
    code: {
      typescript: `export class StripeAPI {\n  charge(params: { amount_in_cents: number; currency_code: string }): { id: string; status: string } {\n    return { id: 'ch_' + Math.random().toString(36).slice(2), status: 'succeeded' };\n  }\n}\n\nexport class PayPalAPI {\n  processPayment(value: number, coin: string): { confirmation: string; state: string } {\n    return { confirmation: 'PP-' + Math.random().toString(36).slice(2), state: 'completed' };\n  }\n}`,
      javascript: `class StripeAPI {\n  charge(params) {\n    return { id: 'ch_' + Math.random().toString(36).slice(2), status: 'succeeded' };\n  }\n}\n\nclass PayPalAPI {\n  processPayment(value, coin) {\n    return { confirmation: 'PP-' + Math.random().toString(36).slice(2), state: 'completed' };\n  }\n}`,
    },
  },
  {
    index: 2,
    title: "Definí PaymentProvider y creá StripeAdapter",
    explanation: `Ahora creamos la **clase objetivo** (\`PaymentProvider\`) y el primer adaptador.\n\n\`PaymentProvider\` es la clase base que el cliente va a usar. Define \`pay(amount)\` y \`refund(transactionId)\` — esta es la interfaz unificada que todos los adaptadores deben extender.\n\n\`StripeAdapter\` **extiende** \`PaymentProvider\` y en su constructor recibe una instancia de \`StripeAPI\`. Cuando el cliente llama a \`pay(amount)\`, el adaptador:\n1. Convierte el monto de dólares a centavos (\`amount * 100\`)\n2. Llama a \`this.stripe.charge({ amount_in_cents, currency_code: 'usd' })\`\n3. Devuelve el resultado en el formato que el cliente espera\n\n**El adaptador es un traductor**: recibe la llamada en el idioma del cliente (\`pay\`) y la traduce al idioma del proveedor (\`charge\`).`,
    code: {
      typescript: `export class StripeAPI {\n  charge(params: { amount_in_cents: number; currency_code: string }): { id: string; status: string } {\n    return { id: 'ch_' + Math.random().toString(36).slice(2), status: 'succeeded' };\n  }\n}\n\nexport class PayPalAPI {\n  processPayment(value: number, coin: string): { confirmation: string; state: string } {\n    return { confirmation: 'PP-' + Math.random().toString(36).slice(2), state: 'completed' };\n  }\n}\n\nexport class PaymentProvider {\n  pay(amount: number): { id: string; status: string } {\n    return { id: '', status: '' };\n  }\n\n  refund(transactionId: string): boolean {\n    return false;\n  }\n}\n\nexport class StripeAdapter extends PaymentProvider {\n  private stripe: StripeAPI;\n\n  constructor(stripe: StripeAPI) {\n    super();\n    this.stripe = stripe;\n  }\n\n  pay(amount: number): { id: string; status: string } {\n    return this.stripe.charge({ amount_in_cents: amount * 100, currency_code: 'usd' });\n  }\n\n  refund(transactionId: string): boolean {\n    return true;\n  }\n}`,
      javascript: `class StripeAPI {\n  charge(params) {\n    return { id: 'ch_' + Math.random().toString(36).slice(2), status: 'succeeded' };\n  }\n}\n\nclass PayPalAPI {\n  processPayment(value, coin) {\n    return { confirmation: 'PP-' + Math.random().toString(36).slice(2), state: 'completed' };\n  }\n}\n\nclass PaymentProvider {\n  pay(amount) {\n    return { id: '', status: '' };\n  }\n\n  refund(transactionId) {\n    return false;\n  }\n}\n\nclass StripeAdapter extends PaymentProvider {\n  constructor(stripe) {\n    super();\n    this.stripe = stripe;\n  }\n\n  pay(amount) {\n    return this.stripe.charge({ amount_in_cents: amount * 100, currency_code: 'usd' });\n  }\n\n  refund(transactionId) {\n    return true;\n  }\n}`,
    },
  },
  {
    index: 3,
    title: "Creá PayPalAdapter y la función checkout()",
    explanation: `El patrón se completa con \`PayPalAdapter\` y la función \`checkout()\`.\n\n\`PayPalAdapter\` hace lo mismo que \`StripeAdapter\` pero para PayPal: extiende \`PaymentProvider\`, recibe una \`PayPalAPI\` en el constructor, y cuando llaman a \`pay(amount)\` traduce a \`processPayment(amount, 'USD')\`. El formato de retorno de PayPal es diferente (\`confirmation\` y \`state\` en vez de \`id\` y \`status\`), así que el adaptador también normaliza eso.\n\n\`checkout()\` es la función cliente — recibe un \`PaymentProvider\` y un monto. **No sabe** si por detrás hay un StripeAdapter o un PayPalAdapter. Simplemente llama a \`provider.pay(amount)\`.\n\n**Esto es el poder del patrón Adapter**: el código cliente está completamente desacoplado de los proveedores concretos. Podés agregar cualquier otro proveedor creando un nuevo adaptador sin tocar checkout().\n\n**Resultado final**: las APIs incompatibles conviven bajo una interfaz común.`,
    code: {
      typescript: `export class StripeAPI {\n  charge(params: { amount_in_cents: number; currency_code: string }): { id: string; status: string } {\n    return { id: 'ch_' + Math.random().toString(36).slice(2), status: 'succeeded' };\n  }\n}\n\nexport class PayPalAPI {\n  processPayment(value: number, coin: string): { confirmation: string; state: string } {\n    return { confirmation: 'PP-' + Math.random().toString(36).slice(2), state: 'completed' };\n  }\n}\n\nexport class PaymentProvider {\n  pay(amount: number): { id: string; status: string } {\n    return { id: '', status: '' };\n  }\n\n  refund(transactionId: string): boolean {\n    return false;\n  }\n}\n\nexport class StripeAdapter extends PaymentProvider {\n  private stripe: StripeAPI;\n\n  constructor(stripe: StripeAPI) {\n    super();\n    this.stripe = stripe;\n  }\n\n  pay(amount: number): { id: string; status: string } {\n    return this.stripe.charge({ amount_in_cents: amount * 100, currency_code: 'usd' });\n  }\n\n  refund(transactionId: string): boolean {\n    return true;\n  }\n}\n\nexport class PayPalAdapter extends PaymentProvider {\n  private paypal: PayPalAPI;\n\n  constructor(paypal: PayPalAPI) {\n    super();\n    this.paypal = paypal;\n  }\n\n  pay(amount: number): { id: string; status: string } {\n    const result = this.paypal.processPayment(amount, 'USD');\n    return { id: result.confirmation, status: result.state };\n  }\n\n  refund(transactionId: string): boolean {\n    return true;\n  }\n}\n\nexport function checkout(provider: PaymentProvider, amount: number): { id: string; status: string } {\n  return provider.pay(amount);\n}`,
      javascript: `class StripeAPI {\n  charge(params) {\n    return { id: 'ch_' + Math.random().toString(36).slice(2), status: 'succeeded' };\n  }\n}\n\nclass PayPalAPI {\n  processPayment(value, coin) {\n    return { confirmation: 'PP-' + Math.random().toString(36).slice(2), state: 'completed' };\n  }\n}\n\nclass PaymentProvider {\n  pay(amount) {\n    return { id: '', status: '' };\n  }\n\n  refund(transactionId) {\n    return false;\n  }\n}\n\nclass StripeAdapter extends PaymentProvider {\n  constructor(stripe) {\n    super();\n    this.stripe = stripe;\n  }\n\n  pay(amount) {\n    return this.stripe.charge({ amount_in_cents: amount * 100, currency_code: 'usd' });\n  }\n\n  refund(transactionId) {\n    return true;\n  }\n}\n\nclass PayPalAdapter extends PaymentProvider {\n  constructor(paypal) {\n    super();\n    this.paypal = paypal;\n  }\n\n  pay(amount) {\n    const result = this.paypal.processPayment(amount, 'USD');\n    return { id: result.confirmation, status: result.state };\n  }\n\n  refund(transactionId) {\n    return true;\n  }\n}\n\nfunction checkout(provider, amount) {\n  return provider.pay(amount);\n}`,
    },
  },
];

export const adapterGuided = buildGuidedExercise(
  "adapter",
  "Adapter — Modo Guiado",
  steps
);
