import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "El problema del telescoping constructor",
    explanation: `El patrón **Builder** resuelve el problema del **telescoping constructor**: cuando un objeto tiene muchos parámetros, el constructor se vuelve ilegible y propenso a errores. Mirá este ejemplo — un constructor con 12 parámetros donde la mayoría son \`null\`. ¿Qué significa cada \`null\`? ¿El tercero es RAM o almacenamiento?\n\n**El ejercicio de este patrón**: vamos a construir PCs con diferentes configuraciones (gaming, office, server). En vez de un constructor gigante, vamos a crear un \`ComputerBuilder\` con métodos encadenables. Después, \`GamingComputerBuilder\` va a preconfigurar specs de alto rendimiento y \`OfficeComputerBuilder\` specs básicas. Finalmente, un \`ComputerDirector\` va a encapsular recetas predefinidas.\n\n**Conceptos clave**: la construcción se separa de la representación. El mismo proceso de construcción (setCPU → setGPU → setRAM → build) puede generar resultados completamente diferentes según las elecciones en cada paso.`,
    code: {
      typescript: `// ❌ ANTES: Telescoping constructor — ¿qué es cada null?\nclass Computer {\n  constructor(\n    public cpu: string,\n    public gpu: string,\n    public ram: string,\n    public storage: string,\n    public cooler: string,\n    public psu: string,\n    public motherboard: string,\n    public case_: string,\n    public monitor: string,\n    public keyboard: string,\n    public mouse: string,\n    public headset: string\n  ) {}\n}\n\n// ¿Qué es cada null?\nconst pc = new Computer(\n  'i9', 'RTX 4090', '32GB', '2TB',\n  null, null, null, null, null, null, null, null\n);`,
      javascript: `// ❌ ANTES: Telescoping constructor — ¿qué es cada null?\nclass Computer {\n  constructor(cpu, gpu, ram, storage, cooler, psu, motherboard, case_, monitor, keyboard, mouse, headset) {\n    this.cpu = cpu;\n    this.gpu = gpu;\n    this.ram = ram;\n    this.storage = storage;\n    this.cooler = cooler;\n    this.psu = psu;\n    this.motherboard = motherboard;\n    this.case_ = case_;\n    this.monitor = monitor;\n    this.keyboard = keyboard;\n    this.mouse = mouse;\n    this.headset = headset;\n  }\n}\n\n// ¿Qué es cada null?\nconst pc = new Computer(\n  'i9', 'RTX 4090', '32GB', '2TB',\n  null, null, null, null, null, null, null, null\n);`,
    },
  },
  {
    index: 1,
    title: "Definí Computer y ComputerBuilder con setters encadenables",
    explanation: `Ahora creamos el producto (\`Computer\`) y el builder base (\`ComputerBuilder\`). La clave está en que cada setter retorna \`this\` — eso permite el **method chaining**: \`builder.setCPU('i9').setGPU('RTX').setRAM('32GB').build()\`.\n\n\`ComputerBuilder\` tiene propiedades protegidas (\`cpu\`, \`gpu\`, \`ram\`, \`storage\`) que empiezan vacías. Cada setter asigna el valor y retorna \`this\` para permitir encadenamiento. El método \`build()\` crea y retorna una nueva instancia de \`Computer\` con los valores configurados.\n\n**Por qué \`return this\`**: es lo que hace que los setters sean encadenables. Sin eso, cada llamada retornaría \`undefined\` y no podrías hacer \`.setCPU().setGPU().setRAM()\`. Es un patrón muy común en APIs modernas (jQuery, lodash, query builders de SQL).`,
    code: {
      typescript: `class Computer {\n  constructor(\n    public cpu: string = '',\n    public gpu: string = '',\n    public ram: string = '',\n    public storage: string = ''\n  ) {}\n}\n\nclass ComputerBuilder {\n  protected cpu: string = '';\n  protected gpu: string = '';\n  protected ram: string = '';\n  protected storage: string = '';\n\n  setCPU(cpu: string): this {\n    this.cpu = cpu;\n    return this;\n  }\n\n  setGPU(gpu: string): this {\n    this.gpu = gpu;\n    return this;\n  }\n\n  setRAM(ram: string): this {\n    this.ram = ram;\n    return this;\n  }\n\n  setStorage(storage: string): this {\n    this.storage = storage;\n    return this;\n  }\n\n  build(): Computer {\n    return new Computer(this.cpu, this.gpu, this.ram, this.storage);\n  }\n}`,
      javascript: `class Computer {\n  constructor(cpu = '', gpu = '', ram = '', storage = '') {\n    this.cpu = cpu;\n    this.gpu = gpu;\n    this.ram = ram;\n    this.storage = storage;\n  }\n}\n\nclass ComputerBuilder {\n  constructor() {\n    this.cpu = '';\n    this.gpu = '';\n    this.ram = '';\n    this.storage = '';\n  }\n\n  setCPU(cpu) {\n    this.cpu = cpu;\n    return this;\n  }\n\n  setGPU(gpu) {\n    this.gpu = gpu;\n    return this;\n  }\n\n  setRAM(ram) {\n    this.ram = ram;\n    return this;\n  }\n\n  setStorage(storage) {\n    this.storage = storage;\n    return this;\n  }\n\n  build() {\n    return new Computer(this.cpu, this.gpu, this.ram, this.storage);\n  }\n}`,
    },
  },
  {
    index: 2,
    title: "Implementá GamingComputerBuilder y OfficeComputerBuilder",
    explanation: `Los **builders concretos** extienden \`ComputerBuilder\` y preconfiguran specs específicas en su constructor. \`GamingComputerBuilder\` setea componentes de alto rendimiento (i9, RTX 4090, 32GB DDR5, NVMe). \`OfficeComputerBuilder\` setea componentes básicos (i5, UHD Graphics, 8GB DDR4, SSD SATA).\n\n**La magia**: como extienden \`ComputerBuilder\`, heredan todos los setters encadenables. Podés usarlos directamente (\`new GamingComputerBuilder().build()\`) o personalizar después (\`new GamingComputerBuilder().setRAM('64GB').build()\`). Los builders concretos encapsulan la configuración por defecto sin perder flexibilidad.\n\n**Patrón en acción**: cada builder es una receta lista para usar. No necesitás recordar qué componentes van con qué configuración — el builder ya sabe.`,
    code: {
      typescript: `class Computer {\n  constructor(\n    public cpu: string = '',\n    public gpu: string = '',\n    public ram: string = '',\n    public storage: string = ''\n  ) {}\n}\n\nclass ComputerBuilder {\n  protected cpu: string = '';\n  protected gpu: string = '';\n  protected ram: string = '';\n  protected storage: string = '';\n\n  setCPU(cpu: string): this { this.cpu = cpu; return this; }\n  setGPU(gpu: string): this { this.gpu = gpu; return this; }\n  setRAM(ram: string): this { this.ram = ram; return this; }\n  setStorage(storage: string): this { this.storage = storage; return this; }\n  build(): Computer { return new Computer(this.cpu, this.gpu, this.ram, this.storage); }\n}\n\nclass GamingComputerBuilder extends ComputerBuilder {\n  constructor() {\n    super();\n    this.setCPU('Intel i9-13900K');\n    this.setGPU('NVIDIA RTX 4090');\n    this.setRAM('32GB DDR5');\n    this.setStorage('2TB SSD NVMe');\n  }\n}\n\nclass OfficeComputerBuilder extends ComputerBuilder {\n  constructor() {\n    super();\n    this.setCPU('Intel i5-13400');\n    this.setGPU('Intel UHD Graphics');\n    this.setRAM('8GB DDR4');\n    this.setStorage('512GB SSD SATA');\n  }\n}`,
      javascript: `class Computer {\n  constructor(cpu = '', gpu = '', ram = '', storage = '') {\n    this.cpu = cpu;\n    this.gpu = gpu;\n    this.ram = ram;\n    this.storage = storage;\n  }\n}\n\nclass ComputerBuilder {\n  constructor() {\n    this.cpu = '';\n    this.gpu = '';\n    this.ram = '';\n    this.storage = '';\n  }\n\n  setCPU(cpu) { this.cpu = cpu; return this; }\n  setGPU(gpu) { this.gpu = gpu; return this; }\n  setRAM(ram) { this.ram = ram; return this; }\n  setStorage(storage) { this.storage = storage; return this; }\n  build() { return new Computer(this.cpu, this.gpu, this.ram, this.storage); }\n}\n\nclass GamingComputerBuilder extends ComputerBuilder {\n  constructor() {\n    super();\n    this.setCPU('Intel i9-13900K');\n    this.setGPU('NVIDIA RTX 4090');\n    this.setRAM('32GB DDR5');\n    this.setStorage('2TB SSD NVMe');\n  }\n}\n\nclass OfficeComputerBuilder extends ComputerBuilder {\n  constructor() {\n    super();\n    this.setCPU('Intel i5-13400');\n    this.setGPU('Intel UHD Graphics');\n    this.setRAM('8GB DDR4');\n    this.setStorage('512GB SSD SATA');\n  }\n}`,
    },
  },
  {
    index: 3,
    title: "Creá ComputerDirector con recetas predefinidas",
    explanation: `El **Director** encapsula recetas predefinidas. En vez de que el código cliente sepa qué builder usar y cómo configurarlo, el Director ofrece métodos estáticos como \`buildGamingPC()\` y \`buildOfficePC()\` que reciben un builder y retornan la computadora lista.\n\n**Antes** — el código cliente tiene que saber todo:\n\`\`\`\nconst builder = new GamingComputerBuilder()\nbuilder.setCPU('i9')\nbuilder.setGPU('RTX')\nconst pc = builder.build()\n\`\`\`\n\n**Después** — el Director encapsula la receta:\n\`\`\`\nconst pc = ComputerDirector.buildGamingPC(new GamingComputerBuilder())\n\`\`\`\n\nEl Director separa la **receta** (qué componentes van juntos) del **proceso de construcción** (cómo se ensamblan). Esto es especialmente útil cuando tenés múltiples configuraciones predefinidas y querés que el código cliente sea simple y declarativo.`,
    code: {
      typescript: `class Computer {\n  constructor(\n    public cpu: string = '',\n    public gpu: string = '',\n    public ram: string = '',\n    public storage: string = ''\n  ) {}\n}\n\nclass ComputerBuilder {\n  protected cpu: string = '';\n  protected gpu: string = '';\n  protected ram: string = '';\n  protected storage: string = '';\n\n  setCPU(cpu: string): this { this.cpu = cpu; return this; }\n  setGPU(gpu: string): this { this.gpu = gpu; return this; }\n  setRAM(ram: string): this { this.ram = ram; return this; }\n  setStorage(storage: string): this { this.storage = storage; return this; }\n  build(): Computer { return new Computer(this.cpu, this.gpu, this.ram, this.storage); }\n}\n\nclass GamingComputerBuilder extends ComputerBuilder {\n  constructor() {\n    super();\n    this.setCPU('Intel i9-13900K');\n    this.setGPU('NVIDIA RTX 4090');\n    this.setRAM('32GB DDR5');\n    this.setStorage('2TB SSD NVMe');\n  }\n}\n\nclass OfficeComputerBuilder extends ComputerBuilder {\n  constructor() {\n    super();\n    this.setCPU('Intel i5-13400');\n    this.setGPU('Intel UHD Graphics');\n    this.setRAM('8GB DDR4');\n    this.setStorage('512GB SSD SATA');\n  }\n}\n\nclass ComputerDirector {\n  static buildGamingPC(builder: ComputerBuilder): Computer {\n    return builder.build();\n  }\n\n  static buildOfficePC(builder: ComputerBuilder): Computer {\n    return builder.build();\n  }\n}\n\n// Demo:\nconst gamingPC = ComputerDirector.buildGamingPC(new GamingComputerBuilder());\nconsole.log(gamingPC);\n\nconst officePC = ComputerDirector.buildOfficePC(new OfficeComputerBuilder());\nconsole.log(officePC);`,
      javascript: `class Computer {\n  constructor(cpu = '', gpu = '', ram = '', storage = '') {\n    this.cpu = cpu;\n    this.gpu = gpu;\n    this.ram = ram;\n    this.storage = storage;\n  }\n}\n\nclass ComputerBuilder {\n  constructor() {\n    this.cpu = '';\n    this.gpu = '';\n    this.ram = '';\n    this.storage = '';\n  }\n\n  setCPU(cpu) { this.cpu = cpu; return this; }\n  setGPU(gpu) { this.gpu = gpu; return this; }\n  setRAM(ram) { this.ram = ram; return this; }\n  setStorage(storage) { this.storage = storage; return this; }\n  build() { return new Computer(this.cpu, this.gpu, this.ram, this.storage); }\n}\n\nclass GamingComputerBuilder extends ComputerBuilder {\n  constructor() {\n    super();\n    this.setCPU('Intel i9-13900K');\n    this.setGPU('NVIDIA RTX 4090');\n    this.setRAM('32GB DDR5');\n    this.setStorage('2TB SSD NVMe');\n  }\n}\n\nclass OfficeComputerBuilder extends ComputerBuilder {\n  constructor() {\n    super();\n    this.setCPU('Intel i5-13400');\n    this.setGPU('Intel UHD Graphics');\n    this.setRAM('8GB DDR4');\n    this.setStorage('512GB SSD SATA');\n  }\n}\n\nclass ComputerDirector {\n  static buildGamingPC(builder) {\n    return builder.build();\n  }\n\n  static buildOfficePC(builder) {\n    return builder.build();\n  }\n}\n\n// Demo:\nconst gamingPC = ComputerDirector.buildGamingPC(new GamingComputerBuilder());\nconsole.log(gamingPC);\n\nconst officePC = ComputerDirector.buildOfficePC(new OfficeComputerBuilder());\nconsole.log(officePC);`,
    },
  },
];

export const builderGuided = buildGuidedExercise(
  "builder",
  "Builder — Modo Guiado",
  steps
);
