import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "Definí la clase base ApprovalHandler",
    explanation: `El patrón **Chain of Responsibility** resuelve un problema clásico: tenés una petición que puede ser manejada por distintos objetos, pero no sabés de antemano cuál la va a procesar. En vez de crear una función gigante con \`if/else\` que verifica el monto y decide quién aprueba, creás una cadena de manejadores donde cada uno decide si puede procesar la petición o la delega al siguiente.\n\n**El ejercicio de este patrón**: actualmente la lógica de aprobación está toda junta en un solo lugar con condicionales. Lo vamos a refactorizar para usar Chain of Responsibility. Todo arranca con la **clase base** \`ApprovalHandler\`, que define el contrato común.\n\n\`setNext(handler)\` encadena los manejadores y retorna el handler pasado (para permitir \`a.setNext(b).setNext(c)\`). \`approve(amount)\` en la clase base simplemente delega al siguiente handler si existe, o retorna un mensaje de fallback si nadie pudo aprobar.\n\n**Conceptos clave**: la clase base no aprueba nada por sí misma — es el **eslabón de la cadena**. Su poder está en que cada handler concreto sobrescribe \`approve()\` y decide si procesa o llama a \`super.approve()\` para delegar.`,
    code: {
      typescript: `class ApprovalHandler {\n  private next: ApprovalHandler | null = null;\n\n  setNext(handler: ApprovalHandler): ApprovalHandler {\n    this.next = handler;\n    return handler;\n  }\n\n  approve(amount: number): string {\n    if (this.next) {\n      return this.next.approve(amount);\n    }\n    return 'Nadie pudo aprobar el gasto';\n  }\n}`,
      javascript: `class ApprovalHandler {\n  constructor() {\n    this.next = null;\n  }\n\n  setNext(handler) {\n    this.next = handler;\n    return handler;\n  }\n\n  approve(amount) {\n    if (this.next) {\n      return this.next.approve(amount);\n    }\n    return 'Nadie pudo aprobar el gasto';\n  }\n}`,
    },
  },
  {
    index: 1,
    title: "Implementá EmployeeHandler y ManagerHandler",
    explanation: `Ahora creamos los **handlers concretos**. Cada clase extiende \`ApprovalHandler\` y sobrescribe \`approve()\` con su propia lógica de aprobación.\n\n\`EmployeeHandler\` aprueba gastos de hasta $100. Si el monto supera ese límite, llama a \`super.approve(amount)\` que delega al siguiente handler en la cadena.\n\n\`ManagerHandler\` aprueba gastos de hasta $1000. Mismo mecanismo: si no puede aprobar, delega.\n\nEsta es la esencia del patrón: cada handler tiene **autonomía** para decidir si procesa o delega. Ninguno necesita conocer a los demás — solo sabe que si no puede aprobar, hay un siguiente en la cadena que puede intentarlo.\n\n**Por qué esto importa**: si mañana necesitás agregar un nuevo nivel (ej. \`VPHandler\`), solo creás una clase nueva y la insertás en la cadena. No modificás ni \`EmployeeHandler\` ni \`ManagerHandler\`. Eso es el **Principio de Abierto/Cerrado (OCP)** en acción.`,
    code: {
      typescript: `class ApprovalHandler {\n  private next: ApprovalHandler | null = null;\n\n  setNext(handler: ApprovalHandler): ApprovalHandler {\n    this.next = handler;\n    return handler;\n  }\n\n  approve(amount: number): string {\n    if (this.next) {\n      return this.next.approve(amount);\n    }\n    return 'Nadie pudo aprobar el gasto';\n  }\n}\n\nclass EmployeeHandler extends ApprovalHandler {\n  approve(amount: number): string {\n    if (amount <= 100) {\n      return 'Employee aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass ManagerHandler extends ApprovalHandler {\n  approve(amount: number): string {\n    if (amount <= 1000) {\n      return 'Manager aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}`,
      javascript: `class ApprovalHandler {\n  constructor() {\n    this.next = null;\n  }\n\n  setNext(handler) {\n    this.next = handler;\n    return handler;\n  }\n\n  approve(amount) {\n    if (this.next) {\n      return this.next.approve(amount);\n    }\n    return 'Nadie pudo aprobar el gasto';\n  }\n}\n\nclass EmployeeHandler extends ApprovalHandler {\n  approve(amount) {\n    if (amount <= 100) {\n      return 'Employee aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass ManagerHandler extends ApprovalHandler {\n  approve(amount) {\n    if (amount <= 1000) {\n      return 'Manager aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}`,
    },
  },
  {
    index: 2,
    title: "Implementá DirectorHandler",
    explanation: `\`DirectorHandler\` es el último eslabón de la cadena. Como el Director puede aprobar **cualquier monto**, no necesita chequear límites ni delegar — simplemente aprueba.\n\nNotá que \`DirectorHandler\` NO llama a \`super.approve()\`. Esto es intencional: es el handler terminal. Si una petición llega a él, siempre se procesa. Esto garantiza que ningún gasto quede sin respuesta.\n\n**El patrón completo hasta ahora**: tenés tres handlers independientes, cada uno con su responsabilidad. Pero todavía no forman una cadena — son piezas sueltas. En el próximo paso vamos a conectarlos.`,
    code: {
      typescript: `class ApprovalHandler {\n  private next: ApprovalHandler | null = null;\n\n  setNext(handler: ApprovalHandler): ApprovalHandler {\n    this.next = handler;\n    return handler;\n  }\n\n  approve(amount: number): string {\n    if (this.next) {\n      return this.next.approve(amount);\n    }\n    return 'Nadie pudo aprobar el gasto';\n  }\n}\n\nclass EmployeeHandler extends ApprovalHandler {\n  approve(amount: number): string {\n    if (amount <= 100) {\n      return 'Employee aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass ManagerHandler extends ApprovalHandler {\n  approve(amount: number): string {\n    if (amount <= 1000) {\n      return 'Manager aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass DirectorHandler extends ApprovalHandler {\n  approve(amount: number): string {\n    return 'Director aprobó el gasto de $' + amount;\n  }\n}`,
      javascript: `class ApprovalHandler {\n  constructor() {\n    this.next = null;\n  }\n\n  setNext(handler) {\n    this.next = handler;\n    return handler;\n  }\n\n  approve(amount) {\n    if (this.next) {\n      return this.next.approve(amount);\n    }\n    return 'Nadie pudo aprobar el gasto';\n  }\n}\n\nclass EmployeeHandler extends ApprovalHandler {\n  approve(amount) {\n    if (amount <= 100) {\n      return 'Employee aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass ManagerHandler extends ApprovalHandler {\n  approve(amount) {\n    if (amount <= 1000) {\n      return 'Manager aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass DirectorHandler extends ApprovalHandler {\n  approve(amount) {\n    return 'Director aprobó el gasto de $' + amount;\n  }\n}`,
    },
  },
  {
    index: 3,
    title: "Componé la cadena y probá el flujo completo",
    explanation: `Este es el paso que completa el patrón. Creamos las instancias y las conectamos con \`setNext()\`:\n\n\`\`\`\nconst employee = new EmployeeHandler();\nconst manager = new ManagerHandler();\nconst director = new DirectorHandler();\nemployee.setNext(manager).setNext(director);\n\`\`\`\n\nGracias a que \`setNext()\` retorna el handler pasado, podemos encadenar las llamadas: \`employee → manager → director\`.\n\n**El flujo cuando llamamos \`employee.approve(500)\`**:\n1. \`EmployeeHandler\` verifica: ¿500 ≤ 100? No. Delega con \`super.approve(500)\`.\n2. \`ManagerHandler\` verifica: ¿500 ≤ 1000? Sí. Retorna "Manager aprobó el gasto de $500".\n\n**El flujo cuando llamamos \`employee.approve(5000)\`**:\n1. \`EmployeeHandler\`: 5000 > 100, delega.\n2. \`ManagerHandler\`: 5000 > 1000, delega.\n3. \`DirectorHandler\`: aprueba siempre. Retorna "Director aprobó el gasto de $5000".\n\n**El resultado final**: tenés un sistema donde cada nivel de aprobación está encapsulado en su propia clase, la cadena se puede reordenar o extender sin tocar los handlers existentes, y el código que inicia la aprobación solo conoce al primer handler. Eso es Chain of Responsibility.`,
    code: {
      typescript: `class ApprovalHandler {\n  private next: ApprovalHandler | null = null;\n\n  setNext(handler: ApprovalHandler): ApprovalHandler {\n    this.next = handler;\n    return handler;\n  }\n\n  approve(amount: number): string {\n    if (this.next) {\n      return this.next.approve(amount);\n    }\n    return 'Nadie pudo aprobar el gasto';\n  }\n}\n\nclass EmployeeHandler extends ApprovalHandler {\n  approve(amount: number): string {\n    if (amount <= 100) {\n      return 'Employee aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass ManagerHandler extends ApprovalHandler {\n  approve(amount: number): string {\n    if (amount <= 1000) {\n      return 'Manager aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass DirectorHandler extends ApprovalHandler {\n  approve(amount: number): string {\n    return 'Director aprobó el gasto de $' + amount;\n  }\n}\n\n// Componer la cadena\nconst employee = new EmployeeHandler();\nconst manager = new ManagerHandler();\nconst director = new DirectorHandler();\nemployee.setNext(manager).setNext(director);\n\nconsole.log(employee.approve(50));   // → 'Employee aprobó el gasto de $50'\nconsole.log(employee.approve(500));  // → 'Manager aprobó el gasto de $500'\nconsole.log(employee.approve(5000)); // → 'Director aprobó el gasto de $5000'`,
      javascript: `class ApprovalHandler {\n  constructor() {\n    this.next = null;\n  }\n\n  setNext(handler) {\n    this.next = handler;\n    return handler;\n  }\n\n  approve(amount) {\n    if (this.next) {\n      return this.next.approve(amount);\n    }\n    return 'Nadie pudo aprobar el gasto';\n  }\n}\n\nclass EmployeeHandler extends ApprovalHandler {\n  approve(amount) {\n    if (amount <= 100) {\n      return 'Employee aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass ManagerHandler extends ApprovalHandler {\n  approve(amount) {\n    if (amount <= 1000) {\n      return 'Manager aprobó el gasto de $' + amount;\n    }\n    return super.approve(amount);\n  }\n}\n\nclass DirectorHandler extends ApprovalHandler {\n  approve(amount) {\n    return 'Director aprobó el gasto de $' + amount;\n  }\n}\n\n// Componer la cadena\nconst employee = new EmployeeHandler();\nconst manager = new ManagerHandler();\nconst director = new DirectorHandler();\nemployee.setNext(manager).setNext(director);\n\nconsole.log(employee.approve(50));   // → 'Employee aprobó el gasto de $50'\nconsole.log(employee.approve(500));  // → 'Manager aprobó el gasto de $500'\nconsole.log(employee.approve(5000)); // → 'Director aprobó el gasto de $5000'`,
    },
  },
];

export const chainOfResponsibilityGuided = buildGuidedExercise(
  "chain-of-responsibility",
  "Chain of Responsibility — Modo Guiado",
  steps
);
