import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "Definí la clase base Beverage (y por qué no herencia simple)",
    explanation: `El patrón **Decorator** resuelve un problema clásico: tenés **bebidas** base como **Espresso** y **HouseBlend**, y querés agregar **extras** como **Leche**, **Chocolate** y **Crema** sin que explote la cantidad de clases. El ejercicio pide implementar un sistema de bebidas con extras usando Decorator: cada extra envuelve una bebida y le suma **costo** y **descripción**.\n\nEl problema con la herencia simple es la **explosión de subclases**: si modelás cada combinación con una clase nueva (\`EspressoWithMilk\`, \`EspressoWithMocha\`, \`EspressoWithMilkAndMocha\`...), el número de clases crece exponencialmente con cada aditivo. Agregar un extra nuevo te obliga a crear todas las combinaciones posibles. No escala.\n\nPor eso arrancamos con la **clase base \`Beverage\`**: define el contrato común con \`getCost()\` y \`getDescription()\`. Es una **abstracción** — por sí sola no hace nada útil (devuelve \`0\` y \`''\`), pero establece el comportamiento que tanto las bebidas concretas como los **decoradores** van a respetar. Todo lo que sea un \`Beverage\` puede responder a esos dos métodos sin importar cuántas capas tenga encima. En los próximos pasos vamos a reemplazar las subclases combinadas por decoradores apilables.`,
    code: {
      typescript: `class Beverage {\n  getCost(): number { return 0; }\n  getDescription(): string { return ''; }\n}\n\n// PROBLEMA: con herencia, cada combinación es una subclase nueva\nclass EspressoWithMilk extends Beverage {\n  getCost(): number { return 1.50 + 0.20; }\n  getDescription(): string { return 'Espresso con Leche'; }\n}\n\nclass EspressoWithMocha extends Beverage {\n  getCost(): number { return 1.50 + 0.30; }\n  getDescription(): string { return 'Espresso con Chocolate'; }\n}\n// Espresso con Leche y Chocolate? Otra subclase... explosión de clases`,
      javascript: `class Beverage {\n  getCost() { return 0; }\n  getDescription() { return ''; }\n}\n\n// PROBLEMA: con herencia, cada combinación es una subclase nueva\nclass EspressoWithMilk extends Beverage {\n  getCost() { return 1.50 + 0.20; }\n  getDescription() { return 'Espresso con Leche'; }\n}\n\nclass EspressoWithMocha extends Beverage {\n  getCost() { return 1.50 + 0.30; }\n  getDescription() { return 'Espresso con Chocolate'; }\n}\n// Espresso con Leche y Chocolate? Otra subclase... explosión de clases`,
    },
  },
  {
    index: 1,
    title: "Implementá Espresso y HouseBlend como componentes concretos",
    explanation: `Ahora creamos los **componentes concretos**: las bebidas reales que se pueden servir sin ningún extra. \`Espresso\` cuesta 1.50 y \`HouseBlend\` cuesta 0.89. Cada uno extiende \`Beverage\` y sobrescribe \`getCost()\` y \`getDescription()\` con sus propios valores.\n\nEsta es la esencia del **polimorfismo**: desde afuera, ambas se comportan igual (responden a \`getCost()\` y \`getDescription()\`), pero internamente cada una devuelve su propio costo y su propia descripción. Cualquier código que reciba un \`Beverage\` puede pedirle el costo sin saber si es un espresso o un house blend.\n\n**Por qué esto importa**: cuando más adelante agreguemos un nuevo tipo de bebida (ej. \`DarkRoast\`), el código existente que usa \`Beverage\` no va a cambiar ni una línea. Eso es el **Principio de Abierto/Cerrado (OCP)**: abierto a extensión, cerrado a modificación. La clase base \`Beverage\` quedó igual que en el paso anterior — solo agregamos componentes concretos abajo.`,
    code: {
      typescript: `class Beverage {\n  getCost(): number { return 0; }\n  getDescription(): string { return ''; }\n}\n\nclass Espresso extends Beverage {\n  getCost(): number { return 1.50; }\n  getDescription(): string { return 'Espresso'; }\n}\n\nclass HouseBlend extends Beverage {\n  getCost(): number { return 0.89; }\n  getDescription(): string { return 'House Blend Coffee'; }\n}`,
      javascript: `class Beverage {\n  getCost() { return 0; }\n  getDescription() { return ''; }\n}\n\nclass Espresso extends Beverage {\n  getCost() { return 1.50; }\n  getDescription() { return 'Espresso'; }\n}\n\nclass HouseBlend extends Beverage {\n  getCost() { return 0.89; }\n  getDescription() { return 'House Blend Coffee'; }\n}`,
    },
  },
  {
    index: 2,
    title: "Creá BeverageDecorator que envuelve un beverage y delega",
    explanation: `Acá aparece la pieza central del patrón: **\`BeverageDecorator\`**. Es una clase que **extiende \`Beverage\`** (así puede usarse en cualquier lugar que espere un \`Beverage\`) pero además **guarda una referencia** a otra bebida en \`this.beverage\`. Ese objeto envuelto puede ser un componente concreto (\`Espresso\`) o incluso otro decorador — por eso se pueden apilar.\n\nPor sí solo, \`BeverageDecorator\` no agrega nada: \`getCost()\` y \`getDescription()\` simplemente **delegan** al beverage envuelto. Esto es a propósito: es la base sobre la que los decoradores concretos van a construir. Cada decorador concreto sobrescribe estos métodos para sumar SU costo o SU descripción encima de lo que devuelve el envuelto.\n\n**La clave del patrón**: el decorador tiene el **mismo tipo** que el objeto que envuelve (\`extends Beverage\`). Para el código cliente, envolver un \`Espresso\` con un \`BeverageDecorator\` sigue siendo un \`Beverage\`. Eso es lo que permite apilar capas sin que el cliente sepa — ni le importe — cuántas capas hay. Es **composición sobre herencia**: en vez de crear una subclase por cada combinación, envolvés objetos en tiempo de ejecución.`,
    code: {
      typescript: `class Beverage {\n  getCost(): number { return 0; }\n  getDescription(): string { return ''; }\n}\n\nclass Espresso extends Beverage {\n  getCost(): number { return 1.50; }\n  getDescription(): string { return 'Espresso'; }\n}\n\nclass HouseBlend extends Beverage {\n  getCost(): number { return 0.89; }\n  getDescription(): string { return 'House Blend Coffee'; }\n}\n\nclass BeverageDecorator extends Beverage {\n  constructor(protected beverage: Beverage) { super(); }\n  getCost(): number { return this.beverage.getCost(); }\n  getDescription(): string { return this.beverage.getDescription(); }\n}`,
      javascript: `class Beverage {\n  getCost() { return 0; }\n  getDescription() { return ''; }\n}\n\nclass Espresso extends Beverage {\n  getCost() { return 1.50; }\n  getDescription() { return 'Espresso'; }\n}\n\nclass HouseBlend extends Beverage {\n  getCost() { return 0.89; }\n  getDescription() { return 'House Blend Coffee'; }\n}\n\nclass BeverageDecorator extends Beverage {\n  constructor(beverage) { super(); this.beverage = beverage; }\n  getCost() { return this.beverage.getCost(); }\n  getDescription() { return this.beverage.getDescription(); }\n}`,
    },
  },
  {
    index: 3,
    title: "Implementá Milk, Mocha y Whip como decoradores apilables",
    explanation: `Este es el paso que completa el patrón. Cada decorador concreto extiende \`BeverageDecorator\` y sobrescribe los dos métodos para **sumar** su aporte encima del beverage envuelto:\n\n- \`Milk\` suma \`0.20\` al costo y \`, Leche\` a la descripción.\n- \`Mocha\` suma \`0.30\` al costo y \`, Chocolate\` a la descripción.\n- \`Whip\` suma \`0.15\` al costo y \`, Crema\` a la descripción.\n\nEl truco está en \`this.beverage.getCost() + 0.20\`: el decorador **primero delega** al objeto envuelto (que ya puede tener otras capas) y **después agrega** lo suyo. Como cada capa llama a la siguiente, el costo y la descripción se acumulan de adentro hacia afuera.\n\nEl demo final muestra el **apilado dinámico**: arrancás con un \`Espresso\`, lo envolvés con \`Milk\`, y después envolvés ese resultado con \`Mocha\`. La variable \`beverage\` siempre es de tipo \`Beverage\` — el mismo tipo en cada paso — pero cobró dos capas extra. El costo pasa de 1.50 a 1.70 (con Leche) y luego a 2.00 (con Chocolate)... mirá el código: Espresso (1.50) + Leche (0.20) + Chocolate (0.30) = 2.00.\n\n**El resultado final**: eliminaste la explosión de subclases. Con 2 bebidas y 3 extras, las combinaciones son infinitas y se arman en tiempo de ejecución envolviendo objetos. No creaste ninguna clase combinada — solo 3 decoradores pequeños y reutilizables. Eso es Decorator.`,
    code: {
      typescript: `class Beverage {\n  getCost(): number { return 0; }\n  getDescription(): string { return ''; }\n}\n\nclass Espresso extends Beverage {\n  getCost(): number { return 1.50; }\n  getDescription(): string { return 'Espresso'; }\n}\n\nclass HouseBlend extends Beverage {\n  getCost(): number { return 0.89; }\n  getDescription(): string { return 'House Blend Coffee'; }\n}\n\nclass BeverageDecorator extends Beverage {\n  constructor(protected beverage: Beverage) { super(); }\n  getCost(): number { return this.beverage.getCost(); }\n  getDescription(): string { return this.beverage.getDescription(); }\n}\n\nclass Milk extends BeverageDecorator {\n  getCost(): number { return this.beverage.getCost() + 0.20; }\n  getDescription(): string { return this.beverage.getDescription() + ', Leche'; }\n}\n\nclass Mocha extends BeverageDecorator {\n  getCost(): number { return this.beverage.getCost() + 0.30; }\n  getDescription(): string { return this.beverage.getDescription() + ', Chocolate'; }\n}\n\nclass Whip extends BeverageDecorator {\n  getCost(): number { return this.beverage.getCost() + 0.15; }\n  getDescription(): string { return this.beverage.getDescription() + ', Crema'; }\n}\n\n// Apilado dinámico — cada capa es un Beverage:\nlet beverage: Beverage = new Espresso();\nbeverage = new Milk(beverage);\nbeverage = new Mocha(beverage);\nconsole.log(beverage.getDescription()); // Espresso, Leche, Chocolate\nconsole.log(beverage.getCost());        // 2.00`,
      javascript: `class Beverage {\n  getCost() { return 0; }\n  getDescription() { return ''; }\n}\n\nclass Espresso extends Beverage {\n  getCost() { return 1.50; }\n  getDescription() { return 'Espresso'; }\n}\n\nclass HouseBlend extends Beverage {\n  getCost() { return 0.89; }\n  getDescription() { return 'House Blend Coffee'; }\n}\n\nclass BeverageDecorator extends Beverage {\n  constructor(beverage) { super(); this.beverage = beverage; }\n  getCost() { return this.beverage.getCost(); }\n  getDescription() { return this.beverage.getDescription(); }\n}\n\nclass Milk extends BeverageDecorator {\n  getCost() { return this.beverage.getCost() + 0.20; }\n  getDescription() { return this.beverage.getDescription() + ', Leche'; }\n}\n\nclass Mocha extends BeverageDecorator {\n  getCost() { return this.beverage.getCost() + 0.30; }\n  getDescription() { return this.beverage.getDescription() + ', Chocolate'; }\n}\n\nclass Whip extends BeverageDecorator {\n  getCost() { return this.beverage.getCost() + 0.15; }\n  getDescription() { return this.beverage.getDescription() + ', Crema'; }\n}\n\n// Apilado dinámico — cada capa es un Beverage:\nlet beverage = new Espresso();\nbeverage = new Milk(beverage);\nbeverage = new Mocha(beverage);\nconsole.log(beverage.getDescription()); // Espresso, Leche, Chocolate\nconsole.log(beverage.getCost());        // 2.00`,
    },
  },
];

export const decoratorGuided = buildGuidedExercise(
  "decorator",
  "Decorator — Modo Guiado",
  steps
);