import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "El problema del subsistema complejo",
    explanation: `Imaginá que tenés un sistema de cine en casa con 4 dispositivos: 'Amplifier', 'Projector', 'Screen' y 'SoundSystem'. Para ver una película, necesitás hacer 7-8 llamadas en el orden exacto: encender el amplificador, bajar la pantalla, configurar el proyector, ajustar el sonido... El cliente tiene que conocer cada subsistema y coordinar todo manualmente.\n\nEl patrón **Facade** resuelve esto creando una clase de alto nivel que simplifica la interacción. En vez de que el cliente llame a 8 métodos de 4 objetos distintos, llama a un solo método: \`watchMovie()\` en 'HomeTheaterFacade'.\n\n**Las clases del patrón**: tenés los 4 subsistemas ('Amplifier', 'Projector', 'Screen', 'SoundSystem') y una 'HomeTheaterFacade' que los coordina. La Fachada NO reemplaza al subsistema — solo simplifica su uso. El cliente puede seguir accediendo directamente a los subsistemas si necesita control fino.`,
    code: {
      typescript: `// Sin Facade: el cliente coordina todo manualmente\nconst amp = new Amplifier();\nconst projector = new Projector();\nconst screen = new Screen();\nconst sound = new SoundSystem();\n\n// 8 llamadas en orden exacto\namp.on();\namp.setVolume(8);\nscreen.down();\nprojector.on();\nprojector.setInput("DVD");\nprojector.setWideScreen();\nsound.on();\nsound.setSurround();\n\n// Con Facade: una sola llamada\nconst theater = new HomeTheaterFacade();\ntheater.watchMovie("Inception");`,
      javascript: `// Sin Facade: el cliente coordina todo manualmente\nconst amp = new Amplifier();\nconst projector = new Projector();\nconst screen = new Screen();\nconst sound = new SoundSystem();\n\n// 8 llamadas en orden exacto\namp.on();\namp.setVolume(8);\nscreen.down();\nprojector.on();\nprojector.setInput("DVD");\nprojector.setWideScreen();\nsound.on();\nsound.setSurround();\n\n// Con Facade: una sola llamada\nconst theater = new HomeTheaterFacade();\ntheater.watchMovie("Inception");`,
    },
  },
  {
    index: 1,
    title: "Creá Amplifier y Projector con on/off y configuración",
    explanation: `Los **subsistemas** son las clases que hacen el trabajo real. Cada una tiene sus propios métodos de encendido y configuración. El Amplifier controla el volumen y la fuente de audio. El Projector controla la entrada de video y el modo de pantalla.\n\nEstas clases existen independientemente — no saben nada de la Fachada. Esto es importante: la Fachada las coordina, pero no las modifica. Podés usarlas directamente si necesitás control granular.\n\n**Por qué separar**: cada subsistema tiene una responsabilidad clara. El Amplifier no debería saber cómo funciona el Projector. Cada uno maneja lo suyo.`,
    code: {
      typescript: `class Amplifier {\n  private _on = false;\n\n  on(): void { this._on = true; }\n  off(): void { this._on = false; }\n  isOn(): boolean { return this._on; }\n  setVolume(level: number): void { /* ajustar volumen */ }\n  setInput(input: string): void { /* seleccionar fuente */ }\n}\n\nclass Projector {\n  private _on = false;\n\n  on(): void { this._on = true; }\n  off(): void { this._on = false; }\n  isOn(): boolean { return this._on; }\n  setInput(input: string): void { /* seleccionar entrada */ }\n  setWideScreen(): void { /* modo panorámico */ }\n}`,
      javascript: `class Amplifier {\n  constructor() { this._on = false; }\n\n  on() { this._on = true; }\n  off() { this._on = false; }\n  isOn() { return this._on; }\n  setVolume(level) { /* ajustar volumen */ }\n  setInput(input) { /* seleccionar fuente */ }\n}\n\nclass Projector {\n  constructor() { this._on = false; }\n\n  on() { this._on = true; }\n  off() { this._on = false; }\n  isOn() { return this._on; }\n  setInput(input) { /* seleccionar entrada */ }\n  setWideScreen() { /* modo panorámico */ }\n}`,
    },
  },
  {
    index: 2,
    title: "Creá Screen y SoundSystem",
    explanation: `Dos subsistemas más: la Screen se sube y baja (no tiene on/off como los otros), y el SoundSystem tiene encendido y modo surround.\n\n**Variación interesante**: no todos los subsistemas tienen la misma interfaz. Screen usa \`up()\`/\`down()\` en vez de \`on()\`/\`off()\`. Esto es normal en la realidad — cada dispositivo tiene sus propios controles. La Fachada se encarga de traducir la intención del cliente ("quiero ver una película") a las llamadas específicas de cada subsistema.\n\nEsto demuestra otro beneficio del patrón Facade: el cliente no necesita aprender 4 interfaces distintas. Solo necesita conocer la interfaz simplificada de la Fachada.`,
    code: {
      typescript: `class Amplifier {\n  private _on = false;\n  on(): void { this._on = true; }\n  off(): void { this._on = false; }\n  isOn(): boolean { return this._on; }\n  setVolume(level: number): void {}\n  setInput(input: string): void {}\n}\n\nclass Projector {\n  private _on = false;\n  on(): void { this._on = true; }\n  off(): void { this._on = false; }\n  isOn(): boolean { return this._on; }\n  setInput(input: string): void {}\n  setWideScreen(): void {}\n}\n\nclass Screen {\n  private _down = false;\n  up(): void { this._down = false; }\n  down(): void { this._down = true; }\n  isDown(): boolean { return this._down; }\n}\n\nclass SoundSystem {\n  private _on = false;\n  on(): void { this._on = true; }\n  off(): void { this._on = false; }\n  isOn(): boolean { return this._on; }\n  setSurround(): void {}\n}`,
      javascript: `class Amplifier {\n  constructor() { this._on = false; }\n  on() { this._on = true; }\n  off() { this._on = false; }\n  isOn() { return this._on; }\n  setVolume(level) {}\n  setInput(input) {}\n}\n\nclass Projector {\n  constructor() { this._on = false; }\n  on() { this._on = true; }\n  off() { this._on = false; }\n  isOn() { return this._on; }\n  setInput(input) {}\n  setWideScreen() {}\n}\n\nclass Screen {\n  constructor() { this._down = false; }\n  up() { this._down = false; }\n  down() { this._down = true; }\n  isDown() { return this._down; }\n}\n\nclass SoundSystem {\n  constructor() { this._on = false; }\n  on() { this._on = true; }\n  off() { this._on = false; }\n  isOn() { return this._on; }\n  setSurround() {}\n}`,
    },
  },
  {
    index: 3,
    title: "Creá HomeTheaterFacade con watchMovie() y endMovie()",
    explanation: `Ahora viene la **Fachada**. \`HomeTheaterFacade\` recibe los 4 subsistemas por constructor (inyección de dependencias) y coordina todo con dos métodos simples.\n\n**watchMovie()**: enciende y configura todos los subsistemas en el orden correcto. El cliente llama a un solo método y la Fachada se encarga de todo.\n\n**endMovie()**: apaga todo en orden inverso. Nuevamente, una sola llamada reemplaza 4.\n\n**El resultado final**: el cliente usa \`theater.watchMovie("Inception")\` en vez de 8 llamadas manuales. No necesita saber qué hay detrás — solo sabe que funciona. Eso es Facade: una interfaz simple sobre un sistema complejo.`,
    code: {
      typescript: `class Amplifier {\n  private _on = false;\n  on(): void { this._on = true; }\n  off(): void { this._on = false; }\n  isOn(): boolean { return this._on; }\n  setVolume(level: number): void {}\n  setInput(input: string): void {}\n}\n\nclass Projector {\n  private _on = false;\n  on(): void { this._on = true; }\n  off(): void { this._on = false; }\n  isOn(): boolean { return this._on; }\n  setInput(input: string): void {}\n  setWideScreen(): void {}\n}\n\nclass Screen {\n  private _down = false;\n  up(): void { this._down = false; }\n  down(): void { this._down = true; }\n  isDown(): boolean { return this._down; }\n}\n\nclass SoundSystem {\n  private _on = false;\n  on(): void { this._on = true; }\n  off(): void { this._on = false; }\n  isOn(): boolean { return this._on; }\n  setSurround(): void {}\n}\n\nclass HomeTheaterFacade {\n  private amp: Amplifier;\n  private projector: Projector;\n  private screen: Screen;\n  private sound: SoundSystem;\n\n  constructor(amp?: Amplifier, projector?: Projector, screen?: Screen, sound?: SoundSystem) {\n    this.amp = amp ?? new Amplifier();\n    this.projector = projector ?? new Projector();\n    this.screen = screen ?? new Screen();\n    this.sound = sound ?? new SoundSystem();\n  }\n\n  watchMovie(movie: string): void {\n    this.screen.down();\n    this.projector.on();\n    this.projector.setInput("streaming");\n    this.projector.setWideScreen();\n    this.sound.on();\n    this.sound.setSurround();\n    this.amp.on();\n    this.amp.setVolume(7);\n    this.amp.setInput("streaming");\n  }\n\n  endMovie(): void {\n    this.amp.off();\n    this.sound.off();\n    this.projector.off();\n    this.screen.up();\n  }\n\n  getAmplifier(): Amplifier { return this.amp; }\n  getProjector(): Projector { return this.projector; }\n  getScreen(): Screen { return this.screen; }\n  getSoundSystem(): SoundSystem { return this.sound; }\n}\n\n// Uso:\nconst theater = new HomeTheaterFacade();\ntheater.watchMovie("Inception");\n// ... 2 horas después ...\ntheater.endMovie();`,
      javascript: `class Amplifier {\n  constructor() { this._on = false; }\n  on() { this._on = true; }\n  off() { this._on = false; }\n  isOn() { return this._on; }\n  setVolume(level) {}\n  setInput(input) {}\n}\n\nclass Projector {\n  constructor() { this._on = false; }\n  on() { this._on = true; }\n  off() { this._on = false; }\n  isOn() { return this._on; }\n  setInput(input) {}\n  setWideScreen() {}\n}\n\nclass Screen {\n  constructor() { this._down = false; }\n  up() { this._down = false; }\n  down() { this._down = true; }\n  isDown() { return this._down; }\n}\n\nclass SoundSystem {\n  constructor() { this._on = false; }\n  on() { this._on = true; }\n  off() { this._on = false; }\n  isOn() { return this._on; }\n  setSurround() {}\n}\n\nclass HomeTheaterFacade {\n  constructor(amp, projector, screen, sound) {\n    this.amp = amp ?? new Amplifier();\n    this.projector = projector ?? new Projector();\n    this.screen = screen ?? new Screen();\n    this.sound = sound ?? new SoundSystem();\n  }\n\n  watchMovie(movie) {\n    this.screen.down();\n    this.projector.on();\n    this.projector.setInput("streaming");\n    this.projector.setWideScreen();\n    this.sound.on();\n    this.sound.setSurround();\n    this.amp.on();\n    this.amp.setVolume(7);\n    this.amp.setInput("streaming");\n  }\n\n  endMovie() {\n    this.amp.off();\n    this.sound.off();\n    this.projector.off();\n    this.screen.up();\n  }\n\n  getAmplifier() { return this.amp; }\n  getProjector() { return this.projector; }\n  getScreen() { return this.screen; }\n  getSoundSystem() { return this.sound; }\n}\n\n// Uso:\nconst theater = new HomeTheaterFacade();\ntheater.watchMovie("Inception");\n// ... 2 horas después ...\ntheater.endMovie();`,
    },
  },
];

export const facadeGuided = buildGuidedExercise(
  "facade",
  "Facade — Modo Guiado",
  steps
);
