import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "Definí la clase base Notification",
    explanation: `El patrón **Factory Method** resuelve un problema clásico: tenés un proceso que necesita crear objetos, pero no sabés de antemano qué tipo concreto de objeto vas a necesitar. En vez de llenar tu código de condiciones (\`if tipo === "email"\`), definís una clase base común para los productos y dejás que una fábrica decida qué clase concreta instanciar.\n\n**El ejercicio de este patrón**: actualmente \`NotificationService\` usa condicionales para crear notificaciones. Lo vamos a refactorizar para usar el patrón Factory Method. Todo arranca con el **producto**, que es la clase base que establece el contrato. \`Notification\` define el método \`send(message)\` que TODAS las notificaciones concretas van a implementar. NotificationService, por ahora, todavía crea notificaciones a mano — lo vamos a refactorizar en los próximos pasos.\n\n**Conceptos clave**: la clase base no hace nada útil por sí misma — es una **abstracción**. Su poder está en que cualquier código que reciba un \`Notification\` puede llamar a \`send()\` sin importar si la implementación concreta es email, SMS o push.`,
    code: {
      typescript: `class Notification {\n  send(message: string): void {\n    // Método base — las implementaciones concretas sobrescribirán\n  }\n}\n\nclass NotificationService {\n  notify(type: string, message: string) {\n    // TODO: Refactorizá para usar factory\n  }\n}`,
      javascript: `class Notification {\n  send(message) {\n    // Método base — las implementaciones concretas sobrescribirán\n  }\n}\n\nclass NotificationService {\n  notify(type, message) {\n    // TODO: Refactorizá para usar factory\n  }\n}`,
    },
  },
  {
    index: 1,
    title: "Implementá los tipos de notificación concretos",
    explanation: `Ahora creamos los **productos concretos**. Cada clase extiende \`Notification\` y sobrescribe \`send()\` con su propia lógica. \`EmailNotification\` envía un email, \`SMSNotification\` envía un mensaje de texto, \`PushNotification\` envía una notificación push.\n\nEsta es la esencia del **polimorfismo**: desde afuera, todas se comportan igual (tienen \`send()\`), pero internamente cada una hace algo distinto. Esto permite que el código que las usa no necesite saber qué tipo concreto está manejando — simplemente llama a \`send()\` y cada una responde como corresponde.\n\n**Por qué esto es importante**: cuando más adelante agreguemos un nuevo tipo (ej. SlackNotification), el código existente que usa \`Notification\` no va a cambiar ni una línea. Eso es el **Principio de Abierto/Cerrado (OCP)**: abierto a extensión, cerrado a modificación.\n\nNotá que NotificationService sigue igual que antes — en los próximos pasos lo vamos a transformar para que deje de depender directamente de estas clases concretas.`,
    code: {
      typescript: `class Notification {\n  send(message: string): void {}\n}\n\nclass EmailNotification extends Notification {\n  send(message: string): void {\n    // Implementación para email\n  }\n}\n\nclass SMSNotification extends Notification {\n  send(message: string): void {\n    // Implementación para SMS\n  }\n}\n\nclass PushNotification extends Notification {\n  send(message: string): void {\n    // Implementación para push\n  }\n}\n\nclass NotificationService {\n  notify(type: string, message: string) {\n    // TODO: Refactorizá para usar factory\n  }\n}`,
      javascript: `class Notification {\n  send(message) {}\n}\n\nclass EmailNotification extends Notification {\n  send(message) {\n    // Implementación para email\n  }\n}\n\nclass SMSNotification extends Notification {\n  send(message) {\n    // Implementación para SMS\n  }\n}\n\nclass PushNotification extends Notification {\n  send(message) {\n    // Implementación para push\n  }\n}\n\nclass NotificationService {\n  notify(type, message) {\n    // TODO: Refactorizá para usar factory\n  }\n}`,
    },
  },
  {
    index: 2,
    title: "Creá el NotificationFactory",
    explanation: `Hasta ahora, si alguien necesita crear una notificación, tiene que saber qué clase instanciar: \`new EmailNotification()\`, \`new SMSNotification()\`, etc. La **fábrica** encapsula esa decisión. En lugar de que el código cliente decida, le decís a la fábrica "dame una notificación de tipo email" y ella se encarga de instanciar la clase correcta.\n\n\`NotificationFactory.createNotification(type)\` recibe un string y devuelve la implementación concreta que corresponda usando un \`switch\`. Si el tipo no existe, lanza un error. Esto centraliza la lógica de creación en UN solo lugar.\n\n**Esto es Factory Method en acción**: la fábrica es el "método creador". El código que llama a \`createNotification()\` no necesita saber que existe \`EmailNotification\`, \`SMSNotification\` o \`PushNotification\` — solo sabe que recibe un \`Notification\` y puede llamar a \`send()\`.\n\nA esto se le llama **separación de responsabilidades**: la fábrica se ocupa de CÓMO se crean los objetos; el código cliente se ocupa de CÓMO se USAN. Nunca se mezclan.\n\nAhora sí, en el próximo paso, vamos a conectar todo: \`NotificationService\` va a recibir la fábrica y delegar la creación.`,
    code: {
      typescript: `class Notification {\n  send(message: string): void {}\n}\n\nclass EmailNotification extends Notification {\n  send(message: string): void {}\n}\n\nclass SMSNotification extends Notification {\n  send(message: string): void {}\n}\n\nclass PushNotification extends Notification {\n  send(message: string): void {}\n}\n\nclass NotificationFactory {\n  createNotification(type: string): Notification {\n    switch (type.toLowerCase()) {\n      case "email": return new EmailNotification();\n      case "sms": return new SMSNotification();\n      case "push": return new PushNotification();\n      default: throw new Error(\`Unknown notification type: \${type}\`);\n    }\n  }\n}\n\nclass NotificationService {\n  notify(type: string, message: string) {\n    // TODO: Refactorizá para usar factory\n  }\n}`,
      javascript: `class Notification {\n  send(message) {}\n}\n\nclass EmailNotification extends Notification {\n  send(message) {}\n}\n\nclass SMSNotification extends Notification {\n  send(message) {}\n}\n\nclass PushNotification extends Notification {\n  send(message) {}\n}\n\nclass NotificationFactory {\n  createNotification(type) {\n    switch (type.toLowerCase()) {\n      case "email": return new EmailNotification();\n      case "sms": return new SMSNotification();\n      case "push": return new PushNotification();\n      default: throw new Error(\`Unknown notification type: \${type}\`);\n    }\n  }\n}\n\nclass NotificationService {\n  notify(type, message) {\n    // TODO: Refactorizá para usar factory\n  }\n}`,
    },
  },
  {
    index: 3,
    title: "Refactorizá NotificationService para usar la fábrica",
    explanation: `Este es el paso que completa el patrón. \`NotificationService\` ahora recibe la fábrica por constructor (**inyección de dependencias**) y usa \`this.factory.createNotification(type)\` en vez de los condicionales que antes elegían qué clase instanciar.\n\n**Antes** — el servicio decidía qué crear:\n\`\`\`\nif (type === "email") → new EmailNotification()\nelse if (type === "sms") → new SMSNotification()\n\`\`\`\n\n**Después** — el servicio solo usa lo que la fábrica le da:\n\`\`\`\nconst notification = this.factory.createNotification(type)\nnotification.send(message)\n\`\`\`\n\nLa fábrica decide qué crear; el servicio solo usa el resultado. Esto es **inversión de control**: el que crea no es el que usa.\n\nAhora \`NotificationService\` no sabe nada sobre los tipos concretos de notificación — ni siquiera sabe que existen \`EmailNotification\`, \`SMSNotification\` o \`PushNotification\`. Depende únicamente de \`Notification\` (la abstracción) y de \`NotificationFactory\` (el creador). Podés agregar 20 tipos nuevos de notificación sin tocar una línea de \`NotificationService\`.\n\n**El resultado final**: tenés un sistema donde las responsabilidades están claramente separadas, los componentes están desacoplados, y el código es extensible sin ser modificable. Eso es Factory Method.`,
    code: {
      typescript: `class Notification {\n  send(message: string): void {}\n}\n\nclass EmailNotification extends Notification {\n  send(message: string): void {}\n}\n\nclass SMSNotification extends Notification {\n  send(message: string): void {}\n}\n\nclass PushNotification extends Notification {\n  send(message: string): void {}\n}\n\nclass NotificationFactory {\n  createNotification(type: string): Notification {\n    switch (type.toLowerCase()) {\n      case "email": return new EmailNotification();\n      case "sms": return new SMSNotification();\n      case "push": return new PushNotification();\n      default: throw new Error(\`Unknown notification type: \${type}\`);\n    }\n  }\n}\n\nclass NotificationService {\n  private factory: NotificationFactory;\n\n  constructor(factory: NotificationFactory) {\n    this.factory = factory;\n  }\n\n  notify(type: string, message: string): void {\n    const notification = this.factory.createNotification(type);\n    notification.send(message);\n  }\n}`,
      javascript: `class Notification {\n  send(message) {}\n}\n\nclass EmailNotification extends Notification {\n  send(message) {}\n}\n\nclass SMSNotification extends Notification {\n  send(message) {}\n}\n\nclass PushNotification extends Notification {\n  send(message) {}\n}\n\nclass NotificationFactory {\n  createNotification(type) {\n    switch (type.toLowerCase()) {\n      case "email": return new EmailNotification();\n      case "sms": return new SMSNotification();\n      case "push": return new PushNotification();\n      default: throw new Error(\`Unknown notification type: \${type}\`);\n    }\n  }\n}\n\nclass NotificationService {\n  constructor(factory) {\n    this.factory = factory;\n  }\n\n  notify(type, message) {\n    const notification = this.factory.createNotification(type);\n    notification.send(message);\n  }\n}`,
    },
  },
];

export const factoryMethodGuided = buildGuidedExercise(
  "factory-method",
  "Factory Method — Modo Guiado",
  steps
);
