import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "El problema: condicionales por todos lados",
    explanation: `Imaginá un 'Document' que tiene métodos como 'submitForReview()', 'approve()', 'reject()' y 'archive()'. Cada uno de esos métodos tiene un 'if/else' gigante que verifica el estado actual: "¿estoy en Draft? ¿En Review? ¿En Published?". Agregar un nuevo estado significa modificar TODOS los métodos. Esto es frágil, difícil de mantener y viola el Principio de Abierto/Cerrado.\n\n**El patrón State** resuelve esto extrayendo cada comportamiento dependiente del estado en su propia clase. El 'documento' ('Document') delega las acciones a su estado actual, y cada estado decide qué hacer y a qué estado transicionar. Las transiciones entre estados las maneja cada estado concreto: 'DraftState' transiciona a 'ReviewState' con 'submitForReview()', 'ReviewState' transiciona a 'PublishedState' con 'approve()' o vuelve a 'DraftState' con 'reject()', y 'PublishedState' permite archivar.\n\n**En este paso**: empezamos con la clase base 'DocumentState' que define el contrato (los métodos que cada estado debe implementar) y el 'Document' contexto que mantiene una referencia al estado actual y delega todas las acciones.`,
    code: {
      typescript: `class DocumentState {\n  submitForReview(document) {\n    return "Acción no disponible en este estado";\n  }\n\n  approve(document) {\n    return "Acción no disponible en este estado";\n  }\n\n  reject(document) {\n    return "Acción no disponible en este estado";\n  }\n\n  archive(document) {\n    return "Acción no disponible en este estado";\n  }\n}\n\nclass Document {\n  constructor(title) {\n    this.title = title;\n    this.state = null; // TODO: empezar en DraftState\n  }\n\n  setState(state) {\n    this.state = state;\n  }\n\n  getStateName() {\n    return "Unknown"; // TODO: devolver nombre del estado actual\n  }\n\n  submitForReview() {\n    return this.state.submitForReview(this);\n  }\n\n  approve() {\n    return this.state.approve(this);\n  }\n\n  reject() {\n    return this.state.reject(this);\n  }\n\n  archive() {\n    return this.state.archive(this);\n  }\n}`,
      javascript: `class DocumentState {\n  submitForReview(document) {\n    return "Acción no disponible en este estado";\n  }\n\n  approve(document) {\n    return "Acción no disponible en este estado";\n  }\n\n  reject(document) {\n    return "Acción no disponible en este estado";\n  }\n\n  archive(document) {\n    return "Acción no disponible en este estado";\n  }\n}\n\nclass Document {\n  constructor(title) {\n    this.title = title;\n    this.state = null; // TODO: empezar en DraftState\n  }\n\n  setState(state) {\n    this.state = state;\n  }\n\n  getStateName() {\n    return "Unknown"; // TODO: devolver nombre del estado actual\n  }\n\n  submitForReview() {\n    return this.state.submitForReview(this);\n  }\n\n  approve() {\n    return this.state.approve(this);\n  }\n\n  reject() {\n    return this.state.reject(this);\n  }\n\n  archive() {\n    return this.state.archive(this);\n  }\n}`,
    },
  },
  {
    index: 1,
    title: "Implementá DraftState y ReviewState",
    explanation: `Ahora creamos los primeros dos estados concretos. Cada uno extiende \`DocumentState\` y sobrescribe solo los métodos que le corresponden:\n\n**DraftState** — el estado inicial. Solo permite \`submitForReview()\`, que transiciona a ReviewState. \`approve()\` y \`reject()\` no tienen sentido acá (¿cómo aprobás algo que ni se envió?).\n\n**ReviewState** — el documento está siendo revisado. Permite \`approve()\` (transiciona a PublishedState) y \`reject()\` (vuelve a DraftState). \`submitForReview()\` no tiene sentido porque ya está en revisión.\n\n**La clave**: cada estado conoce a qué otros estados puede transicionar. La transición se hace llamando a \`document.setState(new OtroEstado())\`. El estado tiene el control — el contexto solo delega.\n\nNotá que el \`Document\` ahora arranca en \`DraftState\` y \`getStateName()\` devuelve el nombre correcto.`,
    code: {
      typescript: `class DocumentState {\n  submitForReview(document) { return "Acción no disponible en este estado"; }\n  approve(document) { return "Acción no disponible en este estado"; }\n  reject(document) { return "Acción no disponible en este estado"; }\n  archive(document) { return "Acción no disponible en este estado"; }\n}\n\nclass DraftState extends DocumentState {\n  submitForReview(document) {\n    document.setState(new ReviewState());\n    return "Documento enviado a revisión";\n  }\n\n  approve(document) {\n    return "No se puede aprobar un borrador — primero enviá a revisión";\n  }\n\n  reject(document) {\n    return "No se puede rechazar un borrador — primero enviá a revisión";\n  }\n\n  archive(document) {\n    return "Borrador archivado";\n  }\n}\n\nclass ReviewState extends DocumentState {\n  submitForReview(document) {\n    return "El documento ya está en revisión";\n  }\n\n  approve(document) {\n    document.setState(new PublishedState());\n    return "Documento aprobado y publicado";\n  }\n\n  reject(document) {\n    document.setState(new DraftState());\n    return "Documento rechazado — volvió a borrador";\n  }\n\n  archive(document) {\n    return "Documento en revisión archivado";\n  }\n}\n\nclass Document {\n  constructor(title) {\n    this.title = title;\n    this.state = new DraftState();\n  }\n\n  setState(state) { this.state = state; }\n\n  getStateName() {\n    if (this.state instanceof DraftState) return "Draft";\n    if (this.state instanceof ReviewState) return "Review";\n    return "Unknown";\n  }\n\n  submitForReview() { return this.state.submitForReview(this); }\n  approve() { return this.state.approve(this); }\n  reject() { return this.state.reject(this); }\n  archive() { return this.state.archive(this); }\n}`,
      javascript: `class DocumentState {\n  submitForReview(document) { return "Acción no disponible en este estado"; }\n  approve(document) { return "Acción no disponible en este estado"; }\n  reject(document) { return "Acción no disponible en este estado"; }\n  archive(document) { return "Acción no disponible en este estado"; }\n}\n\nclass DraftState extends DocumentState {\n  submitForReview(document) {\n    document.setState(new ReviewState());\n    return "Documento enviado a revisión";\n  }\n\n  approve(document) {\n    return "No se puede aprobar un borrador — primero enviá a revisión";\n  }\n\n  reject(document) {\n    return "No se puede rechazar un borrador — primero enviá a revisión";\n  }\n\n  archive(document) {\n    return "Borrador archivado";\n  }\n}\n\nclass ReviewState extends DocumentState {\n  submitForReview(document) {\n    return "El documento ya está en revisión";\n  }\n\n  approve(document) {\n    document.setState(new PublishedState());\n    return "Documento aprobado y publicado";\n  }\n\n  reject(document) {\n    document.setState(new DraftState());\n    return "Documento rechazado — volvió a borrador";\n  }\n\n  archive(document) {\n    return "Documento en revisión archivado";\n  }\n}\n\nclass Document {\n  constructor(title) {\n    this.title = title;\n    this.state = new DraftState();\n  }\n\n  setState(state) { this.state = state; }\n\n  getStateName() {\n    if (this.state instanceof DraftState) return "Draft";\n    if (this.state instanceof ReviewState) return "Review";\n    return "Unknown";\n  }\n\n  submitForReview() { return this.state.submitForReview(this); }\n  approve() { return this.state.approve(this); }\n  reject() { return this.state.reject(this); }\n  archive() { return this.state.archive(this); }\n}`,
    },
  },
  {
    index: 2,
    title: "Implementá PublishedState y completá el ciclo",
    explanation: `El último estado concreto: **PublishedState**. Un documento publicado no puede enviarse a revisión (ya pasó por ahí), no puede aprobarse (ya lo está), y no puede rechazarse. Pero sí puede archivarse.\n\nTambién necesitamos un **ArchivedState** para representar el estado final — un documento archivado no puede hacer nada.\n\n**El ciclo completo** queda así:\n\`\`\`\nDraft → submitForReview → Review\nReview → approve → Published\nReview → reject → Draft (loop)\nPublished → archive → Archived (final)\n\`\`\`\n\n**Lo que logramos**: cada estado encapsula su propio comportamiento. Si mañana necesitamos un estado "Rejected" con comportamiento especial, solo creamos una nueva clase — no tocamos ninguna de las existentes. Eso es el Principio de Abierto/Cerrado en acción.\n\nEl \`Document\` contexto no tiene ni un solo \`if/else\` sobre el estado. Solo delega. Los tests verifican el comportamiento completo: transiciones, mensajes de error, y el ciclo de vida entero.`,
    code: {
      typescript: `class DocumentState {\n  submitForReview(document) { return "Acción no disponible en este estado"; }\n  approve(document) { return "Acción no disponible en este estado"; }\n  reject(document) { return "Acción no disponible en este estado"; }\n  archive(document) { return "Acción no disponible en este estado"; }\n}\n\nclass DraftState extends DocumentState {\n  submitForReview(document) {\n    document.setState(new ReviewState());\n    return "Documento enviado a revisión";\n  }\n  approve(document) { return "No se puede aprobar un borrador — primero enviá a revisión"; }\n  reject(document) { return "No se puede rechazar un borrador — primero enviá a revisión"; }\n  archive(document) {\n    document.setState(new ArchivedState());\n    return "Borrador archivado";\n  }\n}\n\nclass ReviewState extends DocumentState {\n  submitForReview(document) { return "El documento ya está en revisión"; }\n  approve(document) {\n    document.setState(new PublishedState());\n    return "Documento aprobado y publicado";\n  }\n  reject(document) {\n    document.setState(new DraftState());\n    return "Documento rechazado — volvió a borrador";\n  }\n  archive(document) {\n    document.setState(new ArchivedState());\n    return "Documento en revisión archivado";\n  }\n}\n\nclass PublishedState extends DocumentState {\n  submitForReview(document) { return "El documento ya está publicado"; }\n  approve(document) { return "El documento ya está publicado"; }\n  reject(document) { return "No se puede rechazar un documento publicado"; }\n  archive(document) {\n    document.setState(new ArchivedState());\n    return "Documento publicado archivado";\n  }\n}\n\nclass ArchivedState extends DocumentState {\n  submitForReview(document) { return "No se puede hacer nada con un documento archivado"; }\n  approve(document) { return "No se puede hacer nada con un documento archivado"; }\n  reject(document) { return "No se puede hacer nada con un documento archivado"; }\n  archive(document) { return "El documento ya está archivado"; }\n}\n\nclass Document {\n  constructor(title) {\n    this.title = title;\n    this.state = new DraftState();\n  }\n\n  setState(state) { this.state = state; }\n\n  getStateName() {\n    if (this.state instanceof DraftState) return "Draft";\n    if (this.state instanceof ReviewState) return "Review";\n    if (this.state instanceof PublishedState) return "Published";\n    if (this.state instanceof ArchivedState) return "Archived";\n    return "Unknown";\n  }\n\n  submitForReview() { return this.state.submitForReview(this); }\n  approve() { return this.state.approve(this); }\n  reject() { return this.state.reject(this); }\n  archive() { return this.state.archive(this); }\n}`,
      javascript: `class DocumentState {\n  submitForReview(document) { return "Acción no disponible en este estado"; }\n  approve(document) { return "Acción no disponible en este estado"; }\n  reject(document) { return "Acción no disponible en este estado"; }\n  archive(document) { return "Acción no disponible en este estado"; }\n}\n\nclass DraftState extends DocumentState {\n  submitForReview(document) {\n    document.setState(new ReviewState());\n    return "Documento enviado a revisión";\n  }\n  approve(document) { return "No se puede aprobar un borrador — primero enviá a revisión"; }\n  reject(document) { return "No se puede rechazar un borrador — primero enviá a revisión"; }\n  archive(document) {\n    document.setState(new ArchivedState());\n    return "Borrador archivado";\n  }\n}\n\nclass ReviewState extends DocumentState {\n  submitForReview(document) { return "El documento ya está en revisión"; }\n  approve(document) {\n    document.setState(new PublishedState());\n    return "Documento aprobado y publicado";\n  }\n  reject(document) {\n    document.setState(new DraftState());\n    return "Documento rechazado — volvió a borrador";\n  }\n  archive(document) {\n    document.setState(new ArchivedState());\n    return "Documento en revisión archivado";\n  }\n}\n\nclass PublishedState extends DocumentState {\n  submitForReview(document) { return "El documento ya está publicado"; }\n  approve(document) { return "El documento ya está publicado"; }\n  reject(document) { return "No se puede rechazar un documento publicado"; }\n  archive(document) {\n    document.setState(new ArchivedState());\n    return "Documento publicado archivado";\n  }\n}\n\nclass ArchivedState extends DocumentState {\n  submitForReview(document) { return "No se puede hacer nada con un documento archivado"; }\n  approve(document) { return "No se puede hacer nada con un documento archivado"; }\n  reject(document) { return "No se puede hacer nada con un documento archivado"; }\n  archive(document) { return "El documento ya está archivado"; }\n}\n\nclass Document {\n  constructor(title) {\n    this.title = title;\n    this.state = new DraftState();\n  }\n\n  setState(state) { this.state = state; }\n\n  getStateName() {\n    if (this.state instanceof DraftState) return "Draft";\n    if (this.state instanceof ReviewState) return "Review";\n    if (this.state instanceof PublishedState) return "Published";\n    if (this.state instanceof ArchivedState) return "Archived";\n    return "Unknown";\n  }\n\n  submitForReview() { return this.state.submitForReview(this); }\n  approve() { return this.state.approve(this); }\n  reject() { return this.state.reject(this); }\n  archive() { return this.state.archive(this); }\n}`,
    },
  },
];

export const stateGuided = buildGuidedExercise(
  "state",
  "State — Modo Guiado",
  steps
);
