import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "Entendé el problema del cálculo condicional de impuestos",
    explanation: `El patrón **Strategy** resuelve un problema clásico: tenés una clase que hace algo de muchas formas distintas y el código se convierte en un monolito de \`if/else\` que crece con cada variante. Acá, \`Order\` calcula impuestos según el país destino — y cada país nuevo te obliga a meterle mano a \`Order\`.\n\n**El ejercicio de este patrón**: actualmente \`Order\` usa una estructura condicional basada en el país destino (ES, US, UK) para decidir cómo calcular los impuestos. Lo vamos a refactorizar para usar \`estrategias concretas\`: cada país tendrá su propia clase que encapsula su fórmula, y \`Order\` delegará en la estrategia que reciba.\n\nMirá el \`calculateTotal(country)\`: si querés agregar Japón, tenés que abrir \`Order\`, sumar otro \`else if\`, y rezar que no rompas nada. Eso viola el Principio de Abierto/Cerrado — el código está cerrado a extensión y abierto a bugs. **Refactorízalo** moviendo cada fórmula a su propia clase estrategia: agregar un país será crear una clase nueva, sin tocar \`Order\`.\n\n**Conceptos clave**: la **estrategia** es la abstracción común (\`TaxStrategy\`) con el contrato \`calculate(amount)\`. Las estrategias concretas (\`SpainTaxStrategy\`, \`USTaxStrategy\`) encapsulan cada variante. El **contexto** (\`Order\`) no sabe qué estrategia concreta recibe — solo la invoca. En este paso todavía no existen las estrategias: ves el problema desnudo. Lo que vas a implementar a partir de acá es el patrón Strategy: extraer las fórmulas a clases y desacoplar \`Order\` del país destino.`,
    code: {
      typescript: `class Order {\n  private amount: number;\n\n  constructor(amount: number) {\n    this.amount = amount;\n  }\n\n  calculateTotal(country: string): number {\n    if (country === "ES") {\n      return this.amount + this.amount * 0.21;\n    } else if (country === "US") {\n      return this.amount + this.amount * 0.07;\n    } else if (country === "UK") {\n      return this.amount + this.amount * 0.20;\n    }\n    return this.amount;\n  }\n}`,
      javascript: `class Order {\n  constructor(amount) {\n    this.amount = amount;\n  }\n\n  calculateTotal(country) {\n    if (country === "ES") {\n      return this.amount + this.amount * 0.21;\n    } else if (country === "US") {\n      return this.amount + this.amount * 0.07;\n    } else if (country === "UK") {\n      return this.amount + this.amount * 0.20;\n    }\n    return this.amount;\n  }\n}`,
    },
  },
  {
    index: 1,
    title: "Extraé las fórmulas a estrategias concretas",
    explanation: `Llegó el momento de extraer las fórmulas. En vez de que \`Order\` sepa que ES cobra 21% y US cobra 7%, movemos cada fórmula a su propia clase — \`Order\` queda intacta por ahora.\n\nPrimero creamos la **estrategia base** \`TaxStrategy\` con el método \`calculate(amount)\` que devuelve \`0\`. Es la abstracción común — el contrato que todas las estrategias concretas van a cumplir. Sin lógica real: su trabajo es definir el método, no implementarlo.\n\nDespués creamos las **estrategias concretas**. \`SpainTaxStrategy extends TaxStrategy\` sobrescribe \`calculate(amount)\` devolviendo \`amount * 0.21\` (el 21% de IVA español). \`USTaxStrategy extends TaxStrategy\` devuelve \`amount * 0.07\` (asumimos 7% como tasa federal promedio). Cada una es una clase independiente, con una sola responsabilidad, testeable de forma aislada.\n\n**Por qué importa**: ahora las fórmulas están encapsuladas. Si mañana cambia el IVA español, solo tocás \`SpainTaxStrategy\`. Si agregás UK, creás \`UKTaxStrategy\` sin modificar nada existente. Esto es el Principio de Abierto/Cerrado en estado puro: abierto a extensión (implementaciones nuevas), cerrado a modificación (no rompés lo que ya funciona).\n\nNotá que \`Order\` sigue igual — todavía tiene el \`if/else\` en \`calculateTotal(country)\`. En el próximo paso lo vamos a reemplazar para que delegue en la estrategia inyectada por constructor.`,
    code: {
      typescript: `class Order {\n  private amount: number;\n\n  constructor(amount: number) {\n    this.amount = amount;\n  }\n\n  calculateTotal(country: string): number {\n    if (country === "ES") {\n      return this.amount + this.amount * 0.21;\n    } else if (country === "US") {\n      return this.amount + this.amount * 0.07;\n    } else if (country === "UK") {\n      return this.amount + this.amount * 0.20;\n    }\n    return this.amount;\n  }\n}\n\nclass TaxStrategy {\n  calculate(amount: number): number {\n    return 0;\n  }\n}\n\nclass SpainTaxStrategy extends TaxStrategy {\n  calculate(amount: number): number {\n    return amount * 0.21;\n  }\n}\n\nclass USTaxStrategy extends TaxStrategy {\n  calculate(amount: number): number {\n    return amount * 0.07;\n  }\n}`,
      javascript: `class Order {\n  constructor(amount) {\n    this.amount = amount;\n  }\n\n  calculateTotal(country) {\n    if (country === "ES") {\n      return this.amount + this.amount * 0.21;\n    } else if (country === "US") {\n      return this.amount + this.amount * 0.07;\n    } else if (country === "UK") {\n      return this.amount + this.amount * 0.20;\n    }\n    return this.amount;\n  }\n}\n\nclass TaxStrategy {\n  calculate(amount) {\n    return 0;\n  }\n}\n\nclass SpainTaxStrategy extends TaxStrategy {\n  calculate(amount) {\n    return amount * 0.21;\n  }\n}\n\nclass USTaxStrategy extends TaxStrategy {\n  calculate(amount) {\n    return amount * 0.07;\n  }\n}`,
    },
  },
  {
    index: 2,
    title: "Refactorizá Order para delegar en la estrategia inyectada",
    explanation: `Este es el paso que completa el patrón. \`Order\` deja de saber de países y pasa a depender solo de la abstracción \`TaxStrategy\`. El constructor recibe una **estrategia inyectada** (no el \`amount\`: el caller elige la estrategia al construir el \`Order\`, y un mismo \`Order\` ya no cambia de fórmula en runtime).\n\n\`calculateTotal(amount)\` ahora es una sola línea: \`return amount + this.strategy.calculate(amount)\`. Sumás el monto base más el impuesto que la estrategia calcule. Si inyectás \`SpainTaxStrategy\`, el tax es 21%. Si inyectás \`USTaxStrategy\`, es 7%. \`Order\` no sabe ni le importa — solo delega.\n\n**Antes**:\n\`\`\`\nif (country === "ES") → amount * 0.21\nelse if (country === "US") → amount * 0.07\n\`\`\`\n\n**Después**:\n\`\`\`\nreturn amount + this.strategy.calculate(amount)\n\`\`\`\n\nEsto es **inversión de control**: \`Order\` ya no decide qué fórmula aplicar — el código que la construye le pasa la estrategia ya elegida. La consecuencia práctica: agregás un país nuevo creando una clase nueva (\`UKTaxStrategy\`, \`JapanTaxStrategy\`) y pasándola al constructor. \`Order\` no cambia ni una línea.\n\n**El resultado final**: tenés \`TaxStrategy\` (abstracción), \`SpainTaxStrategy\` y \`USTaxStrategy\` (estrategias concretas), y \`Order\` (el contexto que delega). Responsabilidades separadas, código desacoplado, fácil de extender, fácil de testear. Eso es Strategy.`,
    code: {
      typescript: `class Order {\n  private strategy: TaxStrategy;\n\n  constructor(strategy: TaxStrategy) {\n    this.strategy = strategy;\n  }\n\n  calculateTotal(amount: number): number {\n    return amount + this.strategy.calculate(amount);\n  }\n}\n\nclass TaxStrategy {\n  calculate(amount: number): number {\n    return 0;\n  }\n}\n\nclass SpainTaxStrategy extends TaxStrategy {\n  calculate(amount: number): number {\n    return amount * 0.21;\n  }\n}\n\nclass USTaxStrategy extends TaxStrategy {\n  calculate(amount: number): number {\n    return amount * 0.07;\n  }\n}`,
      javascript: `class Order {\n  constructor(strategy) {\n    this.strategy = strategy;\n  }\n\n  calculateTotal(amount) {\n    return amount + this.strategy.calculate(amount);\n  }\n}\n\nclass TaxStrategy {\n  calculate(amount) {\n    return 0;\n  }\n}\n\nclass SpainTaxStrategy extends TaxStrategy {\n  calculate(amount) {\n    return amount * 0.21;\n  }\n}\n\nclass USTaxStrategy extends TaxStrategy {\n  calculate(amount) {\n    return amount * 0.07;\n  }\n}`,
    },
  },
];

export const strategyGuided = buildGuidedExercise(
  "strategy",
  "Strategy — Modo Guiado",
  steps
);