import { buildGuidedExercise } from "@/lib/guided-mode/build";
import type { GuidedStepInput } from "@/lib/guided-mode/build";

const steps: GuidedStepInput[] = [
  {
    index: 0,
    title: "Identificá el algoritmo duplicado",
    explanation: `El patrón **Template Method** resuelve un problema clásico: tenés múltiples clases que repiten la misma estructura de algoritmo con ligeras variaciones. Imaginá un generador de reportes: PDF, HTML y CSV todos siguen los mismos pasos — obtener datos, procesarlos, formatear y exportar — pero cada uno implementa esos pasos de forma distinta.\n\nSin Template Method, duplicarías la secuencia en cada clase. Con él, extraés el esqueleto del algoritmo a una clase base y dejás que las subclases redefinan solo los pasos que varían.\n\n**El ejercicio**: partimos de tres clases separadas que repiten el mismo flujo. Vamos a refactorizarlas para extraer un \`ReportGenerator\` base con un template method \`generate()\` que defina el orden fijo de los pasos.\n\n**Conceptos clave**: el template method es el que controla el flujo — las subclases no pueden alterar el orden, solo la implementación de cada paso. Esto garantiza consistencia mientras permite variación.`,
    code: {
      typescript: `// PROBLEMA: Cada generador repite el mismo algoritmo\n// getData → processData → formatOutput → export\n// pero duplica la estructura en cada formato (PDF, HTML, CSV)\n//\n// El Template Method va a extraer el esqueleto común\n// a una clase base ReportGenerator`,
      javascript: `// PROBLEMA: Cada generador repite el mismo algoritmo\n// getData → processData → formatOutput → export\n// pero duplica la estructura en cada formato (PDF, HTML, CSV)\n//\n// El Template Method va a extraer el esqueleto común\n// a una clase base ReportGenerator`,
    },
  },
  {
    index: 1,
    title: "Creá la clase base ReportGenerator con el template method",
    explanation: `Ahora extraemos el esqueleto del algoritmo a una clase base. \`ReportGenerator\` define el template method \`generate()\` que establece el orden fijo de los pasos: \`getData()\` → \`processData()\` → \`formatOutput()\` → \`exportReport()\`.\n\nCada uno de estos métodos tiene una implementación por defecto en la clase base. Las subclases van a sobrescribir los que necesiten variar. La clave: \`generate()\` **nunca se sobrescribe** — es el que garantiza que el orden se mantenga.\n\n**Esto es Template Method en acción**: el algoritmo vive en UN solo lugar. Si mañana necesitás agregar un paso nuevo (ej. validación), lo agregás en \`generate()\` y TODAS las subclases lo heredan automáticamente.\n\n**Principio de Inversión de Dependencias**: la clase base define qué pasos se ejecutan; las subclases definen cómo se ejecutan. El control del flujo está invertido — no es la subclase la que decide el orden.`,
    code: {
      typescript: `class ReportGenerator {\n  // Template Method: define el esqueleto del algoritmo\n  generate(): string {\n    const data = this.getData();\n    const processed = this.processData(data);\n    const formatted = this.formatOutput(processed);\n    return this.exportReport(formatted);\n  }\n\n  // Métodos de pasos — implementación por defecto\n  protected getData(): string[] {\n    return ['item1', 'item2', 'item3'];\n  }\n\n  protected processData(data: string[]): string[] {\n    return data;\n  }\n\n  protected formatOutput(data: string[]): string {\n    return data.join('\\n');\n  }\n\n  protected exportReport(formatted: string): string {\n    return formatted;\n  }\n}`,
      javascript: `class ReportGenerator {\n  // Template Method: define el esqueleto del algoritmo\n  generate() {\n    const data = this.getData();\n    const processed = this.processData(data);\n    const formatted = this.formatOutput(processed);\n    return this.exportReport(formatted);\n  }\n\n  // Métodos de pasos — implementación por defecto\n  getData() {\n    return ['item1', 'item2', 'item3'];\n  }\n\n  processData(data) {\n    return data;\n  }\n\n  formatOutput(data) {\n    return data.join('\\n');\n  }\n\n  exportReport(formatted) {\n    return formatted;\n  }\n}`,
    },
  },
  {
    index: 2,
    title: "Implementá PDFReport como subclase concreta",
    explanation: `Ahora creamos la primera subclase. \`PDFReport\` extiende \`ReportGenerator\` y sobrescribe los métodos de pasos que necesitan variación:\n\n- \`processData()\`: convierte los datos a mayúsculas (formato PDF).\n- \`formatOutput()\`: une los datos con pipes y agrega un prefijo \`[PDF]\`.\n- \`exportReport()\`: simula la exportación con un prefijo.\n\nNotá que NO sobrescribe \`generate()\` — hereda el template method de la clase base. Esto es fundamental: la secuencia del algoritmo está garantizada por la clase base. La subclase solo define los detalles de cada paso.\n\n**Polimorfismo en acción**: si llamás a \`pdfReport.generate()\`, ejecuta el mismo esqueleto que la clase base, pero cada paso usa la implementación de \`PDFReport\`. Si mañana creás \`JSONReport\`, solo necesita sobrescribir los mismos métodos — el esqueleto no cambia.`,
    code: {
      typescript: `class ReportGenerator {\n  generate(): string {\n    const data = this.getData();\n    const processed = this.processData(data);\n    const formatted = this.formatOutput(processed);\n    return this.exportReport(formatted);\n  }\n\n  protected getData(): string[] {\n    return ['item1', 'item2', 'item3'];\n  }\n\n  protected processData(data: string[]): string[] {\n    return data;\n  }\n\n  protected formatOutput(data: string[]): string {\n    return data.join('\\n');\n  }\n\n  protected exportReport(formatted: string): string {\n    return formatted;\n  }\n}\n\nclass PDFReport extends ReportGenerator {\n  protected processData(data: string[]): string[] {\n    return data.map(d => d.toUpperCase());\n  }\n\n  protected formatOutput(data: string[]): string {\n    return '[PDF] ' + data.join(' | ');\n  }\n\n  protected exportReport(formatted: string): string {\n    return 'PDF exported: ' + formatted;\n  }\n}`,
      javascript: `class ReportGenerator {\n  generate() {\n    const data = this.getData();\n    const processed = this.processData(data);\n    const formatted = this.formatOutput(processed);\n    return this.exportReport(formatted);\n  }\n\n  getData() {\n    return ['item1', 'item2', 'item3'];\n  }\n\n  processData(data) {\n    return data;\n  }\n\n  formatOutput(data) {\n    return data.join('\\n');\n  }\n\n  exportReport(formatted) {\n    return formatted;\n  }\n}\n\nclass PDFReport extends ReportGenerator {\n  processData(data) {\n    return data.map(d => d.toUpperCase());\n  }\n\n  formatOutput(data) {\n    return '[PDF] ' + data.join(' | ');\n  }\n\n  exportReport(formatted) {\n    return 'PDF exported: ' + formatted;\n  }\n}`,
    },
  },
  {
    index: 3,
    title: "Implementá HTMLReport y CSVReport — completá el patrón",
    explanation: `Las últimas dos subclases siguen el mismo patrón: extienden \`ReportGenerator\` y sobrescriben los métodos de pasos con su variante específica.\n\n- \`HTMLReport\`: envuelve los datos en tags \`<li>\` y genera una lista \`<ul>\`.\n- \`CSVReport\`: mantiene los datos sin procesar y los formatea como filas CSV con header.\n\n**El resultado final**: tenés 4 clases donde el algoritmo vive en UN solo lugar. Si necesitás agregar un paso (ej. validación de datos), lo agregás en \`generate()\` y las 3 subclases lo heredan. Si necesitás un nuevo formato (ej. JSONReport), creás una subclase sin tocar nada existente.\n\n**Eso es el Principio Abierto/Cerrado (OCP)**: abierto a extensión (nuevas subclases), cerrado a modificación (generate() no cambia). Template Method es uno de los patrones más elegantes para lograr esto.`,
    code: {
      typescript: `class ReportGenerator {\n  generate(): string {\n    const data = this.getData();\n    const processed = this.processData(data);\n    const formatted = this.formatOutput(processed);\n    return this.exportReport(formatted);\n  }\n\n  protected getData(): string[] {\n    return ['item1', 'item2', 'item3'];\n  }\n\n  protected processData(data: string[]): string[] {\n    return data;\n  }\n\n  protected formatOutput(data: string[]): string {\n    return data.join('\\n');\n  }\n\n  protected exportReport(formatted: string): string {\n    return formatted;\n  }\n}\n\nclass PDFReport extends ReportGenerator {\n  protected processData(data: string[]): string[] {\n    return data.map(d => d.toUpperCase());\n  }\n\n  protected formatOutput(data: string[]): string {\n    return '[PDF] ' + data.join(' | ');\n  }\n\n  protected exportReport(formatted: string): string {\n    return 'PDF exported: ' + formatted;\n  }\n}\n\nclass HTMLReport extends ReportGenerator {\n  protected processData(data: string[]): string[] {\n    return data.map(d => '<li>' + d + '</li>');\n  }\n\n  protected formatOutput(data: string[]): string {\n    return '<ul>' + data.join('') + '</ul>';\n  }\n\n  protected exportReport(formatted: string): string {\n    return 'HTML exported: ' + formatted;\n  }\n}\n\nclass CSVReport extends ReportGenerator {\n  protected processData(data: string[]): string[] {\n    return data;\n  }\n\n  protected formatOutput(data: string[]): string {\n    return 'name\\n' + data.join('\\n');\n  }\n\n  protected exportReport(formatted: string): string {\n    return 'CSV exported: ' + formatted;\n  }\n}`,
      javascript: `class ReportGenerator {\n  generate() {\n    const data = this.getData();\n    const processed = this.processData(data);\n    const formatted = this.formatOutput(processed);\n    return this.exportReport(formatted);\n  }\n\n  getData() {\n    return ['item1', 'item2', 'item3'];\n  }\n\n  processData(data) {\n    return data;\n  }\n\n  formatOutput(data) {\n    return data.join('\\n');\n  }\n\n  exportReport(formatted) {\n    return formatted;\n  }\n}\n\nclass PDFReport extends ReportGenerator {\n  processData(data) {\n    return data.map(d => d.toUpperCase());\n  }\n\n  formatOutput(data) {\n    return '[PDF] ' + data.join(' | ');\n  }\n\n  exportReport(formatted) {\n    return 'PDF exported: ' + formatted;\n  }\n}\n\nclass HTMLReport extends ReportGenerator {\n  processData(data) {\n    return data.map(d => '<li>' + d + '</li>');\n  }\n\n  formatOutput(data) {\n    return '<ul>' + data.join('') + '</ul>';\n  }\n\n  exportReport(formatted) {\n    return 'HTML exported: ' + formatted;\n  }\n}\n\nclass CSVReport extends ReportGenerator {\n  processData(data) {\n    return data;\n  }\n\n  formatOutput(data) {\n    return 'name\\n' + data.join('\\n');\n  }\n\n  exportReport(formatted) {\n    return 'CSV exported: ' + formatted;\n  }\n}`,
    },
  },
];

export const templateMethodGuided = buildGuidedExercise(
  "template-method",
  "Template Method — Modo Guiado",
  steps
);
